version: '3.7'

services:
  noname-grpc:
    build: .
    command: >
      sh -c "protoc
      -I=./import/
      -I=/go/src/github.com/gogo/protobuf/protobuf
      --gogofaster_out=Mgogoproto/gogo.proto=github.com/gogo/protobuf/gogoproto,Mgoogle/protobuf/any.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/empty.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/duration.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/field_mask.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/struct.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/timestamp.proto=github.com/gogo/protobuf/types,Mgoogle/protobuf/wrappers.proto=github.com/gogo/protobuf/types,plugins=grpc:./export/pb
      ./import/proto/*.proto ./import/noname.proto"
    volumes:
      - ./src:/home/noname/import
      - ./build:/home/noname/export