// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/mission_category.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MissionCategory struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionCategory) Reset()         { *m = MissionCategory{} }
func (m *MissionCategory) String() string { return proto.CompactTextString(m) }
func (*MissionCategory) ProtoMessage()    {}
func (*MissionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59d103818b3694d, []int{0}
}

func (m *MissionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionCategory.Unmarshal(m, b)
}
func (m *MissionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionCategory.Marshal(b, m, deterministic)
}
func (m *MissionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionCategory.Merge(m, src)
}
func (m *MissionCategory) XXX_Size() int {
	return xxx_messageInfo_MissionCategory.Size(m)
}
func (m *MissionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_MissionCategory proto.InternalMessageInfo

func (m *MissionCategory) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MissionCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MissionCategory) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type MissionResourcesFinding struct {
	ResourceQty          uint32   `protobuf:"varint,1,opt,name=ResourceQty,proto3" json:"ResourceQty,omitempty"`
	ResourceID           uint32   `protobuf:"varint,2,opt,name=ResourceID,proto3" json:"ResourceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionResourcesFinding) Reset()         { *m = MissionResourcesFinding{} }
func (m *MissionResourcesFinding) String() string { return proto.CompactTextString(m) }
func (*MissionResourcesFinding) ProtoMessage()    {}
func (*MissionResourcesFinding) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59d103818b3694d, []int{1}
}

func (m *MissionResourcesFinding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionResourcesFinding.Unmarshal(m, b)
}
func (m *MissionResourcesFinding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionResourcesFinding.Marshal(b, m, deterministic)
}
func (m *MissionResourcesFinding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionResourcesFinding.Merge(m, src)
}
func (m *MissionResourcesFinding) XXX_Size() int {
	return xxx_messageInfo_MissionResourcesFinding.Size(m)
}
func (m *MissionResourcesFinding) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionResourcesFinding.DiscardUnknown(m)
}

var xxx_messageInfo_MissionResourcesFinding proto.InternalMessageInfo

func (m *MissionResourcesFinding) GetResourceQty() uint32 {
	if m != nil {
		return m.ResourceQty
	}
	return 0
}

func (m *MissionResourcesFinding) GetResourceID() uint32 {
	if m != nil {
		return m.ResourceID
	}
	return 0
}

// GetAllMissionCategories
type GetAllMissionCategoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllMissionCategoriesRequest) Reset()         { *m = GetAllMissionCategoriesRequest{} }
func (m *GetAllMissionCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllMissionCategoriesRequest) ProtoMessage()    {}
func (*GetAllMissionCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59d103818b3694d, []int{2}
}

func (m *GetAllMissionCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMissionCategoriesRequest.Unmarshal(m, b)
}
func (m *GetAllMissionCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMissionCategoriesRequest.Marshal(b, m, deterministic)
}
func (m *GetAllMissionCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMissionCategoriesRequest.Merge(m, src)
}
func (m *GetAllMissionCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllMissionCategoriesRequest.Size(m)
}
func (m *GetAllMissionCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMissionCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMissionCategoriesRequest proto.InternalMessageInfo

type GetAllMissionCategoriesResponse struct {
	MissionCategories    []*MissionCategory `protobuf:"bytes,1,rep,name=MissionCategories,proto3" json:"MissionCategories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAllMissionCategoriesResponse) Reset()         { *m = GetAllMissionCategoriesResponse{} }
func (m *GetAllMissionCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllMissionCategoriesResponse) ProtoMessage()    {}
func (*GetAllMissionCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b59d103818b3694d, []int{3}
}

func (m *GetAllMissionCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllMissionCategoriesResponse.Unmarshal(m, b)
}
func (m *GetAllMissionCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllMissionCategoriesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllMissionCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllMissionCategoriesResponse.Merge(m, src)
}
func (m *GetAllMissionCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllMissionCategoriesResponse.Size(m)
}
func (m *GetAllMissionCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllMissionCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllMissionCategoriesResponse proto.InternalMessageInfo

func (m *GetAllMissionCategoriesResponse) GetMissionCategories() []*MissionCategory {
	if m != nil {
		return m.MissionCategories
	}
	return nil
}

func init() {
	proto.RegisterType((*MissionCategory)(nil), "mission_category.MissionCategory")
	proto.RegisterType((*MissionResourcesFinding)(nil), "mission_category.MissionResourcesFinding")
	proto.RegisterType((*GetAllMissionCategoriesRequest)(nil), "mission_category.GetAllMissionCategoriesRequest")
	proto.RegisterType((*GetAllMissionCategoriesResponse)(nil), "mission_category.GetAllMissionCategoriesResponse")
}

func init() { proto.RegisterFile("rpc/mission_category.proto", fileDescriptor_b59d103818b3694d) }

var fileDescriptor_b59d103818b3694d = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2a, 0x48, 0xd6,
	0xcf, 0xcd, 0x2c, 0x2e, 0xce, 0xcc, 0xcf, 0x8b, 0x4f, 0x4e, 0x2c, 0x49, 0x4d, 0xcf, 0x2f, 0xaa,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x40, 0x17, 0x57, 0xf2, 0xe4, 0xe2, 0xf7, 0x85,
	0x88, 0x39, 0x43, 0x85, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78,
	0x83, 0x98, 0x3c, 0x5d, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x70, 0x4e, 0x69, 0xba, 0x04, 0x33, 0x44, 0x0c, 0xc4,
	0x56, 0x8a, 0xe6, 0x12, 0x87, 0x1a, 0x15, 0x94, 0x5a, 0x9c, 0x5f, 0x5a, 0x94, 0x9c, 0x5a, 0xec,
	0x96, 0x99, 0x97, 0x92, 0x99, 0x97, 0x2e, 0xa4, 0xc0, 0xc5, 0x0d, 0x13, 0x0b, 0x2c, 0xa9, 0x84,
	0x9a, 0x8d, 0x2c, 0x24, 0x24, 0xc7, 0xc5, 0x05, 0xe3, 0x7a, 0xba, 0x80, 0xad, 0xe2, 0x0d, 0x42,
	0x12, 0x51, 0x52, 0xe0, 0x92, 0x73, 0x4f, 0x2d, 0x71, 0xcc, 0xc9, 0x41, 0x75, 0x6d, 0x66, 0x6a,
	0x71, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x52, 0x11, 0x97, 0x3c, 0x4e, 0x15, 0xc5, 0x05,
	0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xfe, 0x5c, 0x82, 0x18, 0x92, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0xdc,
	0x46, 0x8a, 0x7a, 0x18, 0x41, 0x86, 0x16, 0x2e, 0x41, 0x98, 0x7a, 0x9d, 0x58, 0xa3, 0x98, 0x8b,
	0x0a, 0x92, 0x93, 0xd8, 0xc0, 0xa1, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xf5, 0x98,
	0xc5, 0x7b, 0x01, 0x00, 0x00,
}
