// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/noname.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("rpc/noname.proto", fileDescriptor_5f9649581b23721b) }

var fileDescriptor_5f9649581b23721b = []byte{
	// 1231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0x59, 0x77, 0xdc, 0x34,
	0x14, 0x2e, 0xd0, 0xa6, 0x45, 0x69, 0x36, 0x35, 0xfb, 0xd2, 0xb4, 0x49, 0x17, 0x4e, 0x17, 0xc3,
	0xa1, 0x2f, 0xf0, 0xc0, 0x43, 0x27, 0x93, 0x86, 0x81, 0x36, 0x98, 0x49, 0x42, 0xe1, 0x1c, 0xa0,
	0x47, 0x4c, 0x94, 0xa9, 0x0f, 0x33, 0xb6, 0x6b, 0x69, 0x80, 0xf9, 0x79, 0xfc, 0xb3, 0x1e, 0x2d,
	0xf7, 0x4a, 0xb6, 0x65, 0x27, 0x6f, 0xa3, 0xef, 0xfb, 0xee, 0x77, 0x25, 0x59, 0xcb, 0xd5, 0x90,
	0xc5, 0x22, 0x1f, 0x7c, 0x99, 0x66, 0x29, 0x1b, 0xf3, 0x28, 0x2f, 0x32, 0x99, 0x6d, 0x2e, 0x28,
	0x84, 0x15, 0xe3, 0xac, 0xb0, 0xc0, 0x3a, 0x02, 0xef, 0x06, 0x4c, 0xf2, 0x61, 0x56, 0x4c, 0x2d,
	0xa3, 0x83, 0xff, 0xe5, 0x2c, 0xcf, 0x52, 0x8b, 0x6c, 0x38, 0x24, 0x28, 0xce, 0x47, 0x6c, 0xca,
	0xc1, 0x78, 0xd5, 0x21, 0xef, 0x84, 0x64, 0xb2, 0xd4, 0x03, 0x9e, 0xf2, 0x31, 0x84, 0xce, 0x2b,
	0x20, 0x91, 0x7c, 0x6c, 0xdb, 0x6b, 0xd0, 0xae, 0xe6, 0xa0, 0x8a, 0x18, 0xb1, 0x74, 0x38, 0x61,
	0x43, 0xee, 0x07, 0x8f, 0x59, 0x2e, 0x6c, 0x7b, 0x4e, 0x8f, 0x38, 0x1f, 0x54, 0xba, 0x95, 0x72,
	0xe9, 0x9b, 0x14, 0x5c, 0x64, 0x93, 0x62, 0x50, 0x32, 0x11, 0xef, 0x93, 0xdc, 0xb6, 0x57, 0x54,
	0x5b, 0x16, 0x2c, 0x15, 0x6c, 0x20, 0x13, 0x1c, 0xfe, 0x92, 0x81, 0xb9, 0x98, 0x14, 0x36, 0xf2,
	0xeb, 0xff, 0xf7, 0xc8, 0xcc, 0x71, 0x76, 0xcc, 0xc6, 0x9c, 0xf6, 0xc8, 0xed, 0x23, 0x2e, 0x5f,
	0xaa, 0x99, 0xec, 0x4c, 0x7b, 0x5d, 0xba, 0x19, 0x99, 0x69, 0xf6, 0xc1, 0x3e, 0xff, 0x30, 0xe1,
	0x42, 0x6e, 0x6e, 0x05, 0x39, 0x91, 0x67, 0xa9, 0xe0, 0x7b, 0xd7, 0x68, 0x9f, 0x2c, 0xbc, 0x4a,
	0xd2, 0x73, 0x4b, 0x69, 0xf7, 0x1d, 0x1b, 0x51, 0xc1, 0xc1, 0xf0, 0x6e, 0x13, 0x8d, 0x9e, 0xaf,
	0xc8, 0xec, 0x59, 0x7e, 0xce, 0x24, 0xd7, 0x34, 0xdd, 0xb0, 0x01, 0x1e, 0x06, 0x5e, 0x9b, 0x21,
	0x0a, 0x7d, 0x72, 0x72, 0x47, 0xf5, 0x7a, 0x34, 0xd2, 0xc4, 0x81, 0xfd, 0x42, 0xf4, 0x49, 0x54,
	0x59, 0x43, 0x01, 0x11, 0x24, 0x78, 0x7a, 0x25, 0x2d, 0x66, 0x3c, 0x26, 0x73, 0x47, 0x5c, 0xc6,
	0x7a, 0x25, 0xe9, 0x99, 0xdd, 0x8e, 0xec, 0x42, 0x2b, 0xc1, 0xe0, 0xbe, 0xd3, 0xc0, 0xa2, 0xdf,
	0x80, 0x2c, 0xab, 0x69, 0x02, 0xee, 0x4c, 0xf0, 0x42, 0x6d, 0x10, 0xba, 0x0f, 0x81, 0x21, 0x16,
	0xdc, 0x1f, 0xb4, 0x8b, 0x30, 0xc9, 0xcf, 0x64, 0x1e, 0xf3, 0x9f, 0x48, 0x26, 0x05, 0xad, 0xf7,
	0x4b, 0xe3, 0xee, 0x0b, 0x36, 0xd0, 0x68, 0x79, 0x4a, 0x16, 0x90, 0xd3, 0x73, 0x25, 0x68, 0x3d,
	0xc8, 0x10, 0x60, 0xba, 0xdb, 0xc8, 0xa3, 0xeb, 0x5b, 0xb2, 0x88, 0xe4, 0x5b, 0xbd, 0xb5, 0x05,
	0xad, 0x87, 0x59, 0x06, 0x7c, 0xef, 0x35, 0x0b, 0xc2, 0x33, 0xf0, 0x3e, 0xc9, 0x83, 0x33, 0xa0,
	0xf0, 0x96, 0x19, 0x30, 0x34, 0x5a, 0x5e, 0x90, 0x15, 0xe4, 0x5e, 0x33, 0x21, 0xe3, 0x4c, 0x24,
	0x6a, 0x7f, 0xd2, 0x07, 0xb5, 0x50, 0x9f, 0x86, 0x04, 0x0f, 0x2f, 0x51, 0x61, 0x9e, 0x6f, 0xc9,
	0xcc, 0x49, 0x32, 0x4c, 0x7b, 0x29, 0x5d, 0x81, 0x10, 0xd3, 0x06, 0xa7, 0xd5, 0x2a, 0xec, 0x77,
	0xf1, 0x0d, 0x4b, 0xd9, 0x90, 0x9b, 0x04, 0xbd, 0xf4, 0x1f, 0x9e, 0x4a, 0xb5, 0x41, 0xb0, 0x8b,
	0x41, 0xba, 0xd6, 0xc5, 0x06, 0x15, 0xe6, 0xf9, 0x83, 0x50, 0x1c, 0x45, 0xdf, 0x9e, 0x66, 0x82,
	0xde, 0xaf, 0x8d, 0x10, 0x39, 0xc8, 0xb0, 0xd7, 0x26, 0x09, 0x7e, 0xbc, 0x9e, 0xe4, 0xe3, 0xd0,
	0xc7, 0xd3, 0x78, 0xf3, 0xc7, 0xb3, 0x74, 0x70, 0xa1, 0x1d, 0x0e, 0xb2, 0x34, 0x1b, 0x4f, 0x03,
	0x0b, 0xcd, 0x32, 0xcd, 0x0b, 0x0d, 0x05, 0x68, 0xfc, 0xa3, 0x3e, 0x78, 0xfb, 0x5c, 0x48, 0xd1,
	0x4b, 0x2f, 0x32, 0xba, 0xe5, 0xc5, 0x20, 0x0a, 0x86, 0xdb, 0x61, 0xd2, 0x3f, 0x6c, 0x0e, 0x61,
	0x63, 0x2b, 0xde, 0x1d, 0x36, 0x25, 0xb8, 0x76, 0xd8, 0x54, 0x58, 0xf4, 0x4b, 0xbc, 0xef, 0xa4,
	0x36, 0x34, 0xd7, 0x27, 0xd8, 0xe3, 0xa8, 0x74, 0x31, 0xd6, 0x15, 0xe0, 0xff, 0xc5, 0xe5, 0x42,
	0x4c, 0x35, 0x21, 0xab, 0x65, 0xfe, 0x34, 0x3b, 0xce, 0x64, 0x72, 0x31, 0xa5, 0x4f, 0xdb, 0x5c,
	0x40, 0x05, 0x29, 0x9f, 0x5d, 0x4d, 0xec, 0xad, 0xf8, 0xa5, 0x83, 0x82, 0x33, 0xc9, 0x3d, 0x19,
	0x7d, 0x54, 0x36, 0xa9, 0x09, 0x20, 0xd9, 0xe3, 0x4b, 0x75, 0x7e, 0x1e, 0x73, 0x23, 0xb5, 0xe4,
	0xa9, 0x09, 0x1a, 0xf2, 0x04, 0x74, 0x7e, 0x9e, 0x2e, 0x1f, 0xf1, 0xd6, 0x3c, 0x35, 0x41, 0x43,
	0x9e, 0x80, 0x0e, 0xf3, 0x98, 0x7a, 0xe1, 0x50, 0x15, 0x42, 0xb6, 0x5e, 0x30, 0x45, 0x91, 0x0f,
	0xba, 0x7a, 0x21, 0xc4, 0xa1, 0xd5, 0x77, 0xe4, 0xd6, 0xf7, 0x89, 0x61, 0xe8, 0xaa, 0x95, 0x02,
	0x00, 0x16, 0x6b, 0x35, 0x1c, 0xc3, 0xbb, 0x64, 0xd6, 0xdc, 0xc0, 0x66, 0xa7, 0xaf, 0x47, 0xba,
	0x18, 0xf3, 0x20, 0xf0, 0xd8, 0x08, 0x30, 0xe8, 0xf2, 0xbb, 0x2e, 0x0c, 0x14, 0xda, 0x99, 0xc2,
	0x2d, 0xde, 0xeb, 0xd2, 0x7b, 0x18, 0x53, 0xa5, 0xc0, 0xf5, 0x7e, 0x8b, 0x02, 0xdd, 0xbf, 0x21,
	0x37, 0xcf, 0x04, 0x57, 0x02, 0xba, 0x6c, 0xf4, 0xb6, 0x09, 0x2e, 0x2b, 0x15, 0x14, 0x23, 0x3f,
	0x90, 0x65, 0xd7, 0x61, 0xeb, 0x9d, 0x70, 0x41, 0x9f, 0x44, 0xe5, 0x1a, 0x33, 0x24, 0x72, 0x15,
	0xcb, 0x55, 0xb4, 0x98, 0x92, 0x11, 0xaa, 0xca, 0x83, 0xd7, 0xb6, 0x54, 0xed, 0x4c, 0x4f, 0x46,
	0x93, 0x21, 0xdd, 0x8f, 0xb0, 0x76, 0xad, 0xb3, 0xae, 0xbe, 0x68, 0x15, 0x61, 0x8a, 0x33, 0x32,
	0x5f, 0xe6, 0xe9, 0x6e, 0x53, 0xa4, 0x3b, 0x4b, 0x1b, 0x05, 0x68, 0xfb, 0x93, 0x5e, 0x94, 0x40,
	0xa9, 0x53, 0x1f, 0x63, 0x7c, 0xdc, 0x9d, 0xfa, 0x0d, 0x34, 0x1a, 0xbe, 0x24, 0xe4, 0x88, 0xcb,
	0x37, 0x2c, 0xd7, 0x6b, 0x7c, 0x2d, 0xd2, 0xa5, 0xba, 0x43, 0xc0, 0x68, 0xbd, 0x4e, 0xa0, 0xc5,
	0x0b, 0x32, 0x63, 0xe6, 0x9b, 0xd2, 0x48, 0x55, 0xf6, 0xa6, 0x01, 0x91, 0x77, 0x4a, 0x18, 0x06,
	0x3d, 0x27, 0xd7, 0x3b, 0x2c, 0xfd, 0x9b, 0x2e, 0x6a, 0x5a, 0xfd, 0x84, 0x80, 0x25, 0x0f, 0x41,
	0xf9, 0x57, 0xe4, 0xc6, 0x41, 0xc1, 0x2e, 0x24, 0x35, 0xac, 0xfe, 0x0d, 0x01, 0xd4, 0x87, 0xea,
	0xb5, 0x48, 0xca, 0x65, 0x67, 0x7a, 0x90, 0x65, 0xc5, 0x79, 0x92, 0xaa, 0xa3, 0x42, 0x5f, 0xf4,
	0xea, 0xbd, 0x11, 0xa4, 0x4b, 0x17, 0x7d, 0x8b, 0x0a, 0xf3, 0xfc, 0xaa, 0xab, 0x3e, 0xb8, 0xa3,
	0x3b, 0x66, 0x4b, 0xe1, 0xfb, 0xa5, 0x42, 0xb9, 0x2d, 0xd5, 0xac, 0x40, 0xe7, 0x3f, 0xc9, 0x52,
	0x89, 0xd4, 0xef, 0x8c, 0xbd, 0x86, 0x48, 0xff, 0xb1, 0xb1, 0xdf, 0xaa, 0xf1, 0xd7, 0x52, 0xb7,
	0xc8, 0x72, 0xe0, 0xe9, 0x8e, 0x0b, 0xf3, 0x71, 0xb7, 0x96, 0x1a, 0x68, 0x34, 0xfc, 0x45, 0x77,
	0x58, 0x15, 0x85, 0x7d, 0x9e, 0xb3, 0xa4, 0xd0, 0xb7, 0xfd, 0xdd, 0x48, 0x3f, 0xdc, 0x6a, 0x84,
	0x2b, 0x81, 0x9b, 0x78, 0xf4, 0x8d, 0xc9, 0xc2, 0x89, 0x64, 0x85, 0x27, 0xa0, 0xdb, 0x26, 0xaa,
	0x02, 0xbb, 0x5b, 0x3f, 0xcc, 0xa2, 0xe3, 0x0f, 0xba, 0x8a, 0xf0, 0xfc, 0x36, 0x4d, 0x44, 0x09,
	0x74, 0x87, 0x7b, 0x88, 0x43, 0x2f, 0xae, 0xaf, 0x75, 0x45, 0x1d, 0xfe, 0x97, 0x8f, 0xb2, 0x82,
	0xa9, 0x62, 0x55, 0x0f, 0x7d, 0xbf, 0x34, 0xb4, 0x0a, 0xeb, 0x0e, 0x94, 0x56, 0x11, 0xa6, 0xf9,
	0x8d, 0x50, 0xdb, 0x03, 0x4f, 0x43, 0x77, 0x4b, 0x7d, 0xf3, 0x18, 0x77, 0xa8, 0x34, 0x0a, 0xd0,
	0xfa, 0x1c, 0x2a, 0x84, 0x53, 0xf7, 0xa4, 0xa6, 0x0f, 0x23, 0xff, 0x81, 0x5d, 0xe3, 0xc1, 0xff,
	0xd1, 0x65, 0x32, 0x6f, 0xce, 0x67, 0xd5, 0xba, 0x39, 0x35, 0xef, 0x73, 0xba, 0x15, 0xc1, 0x4b,
	0xdd, 0x43, 0x5d, 0x15, 0x18, 0x24, 0x2b, 0x4f, 0x4e, 0xf3, 0xa6, 0xb1, 0x4f, 0x4e, 0xfb, 0x47,
	0x48, 0x09, 0x76, 0xeb, 0x21, 0xcc, 0xfa, 0xb5, 0xaf, 0x3a, 0x72, 0x81, 0xd3, 0x3b, 0x6d, 0x17,
	0x82, 0xaa, 0x8c, 0x9b, 0xda, 0x46, 0x81, 0x5f, 0xfb, 0x9a, 0x5a, 0xc6, 0xf0, 0x74, 0x0b, 0x62,
	0x7c, 0xd4, 0x8d, 0x3a, 0x48, 0x7a, 0x05, 0xa4, 0xbd, 0x29, 0x0d, 0x83, 0x6f, 0xfb, 0x67, 0x51,
	0xf5, 0x3f, 0x9f, 0x90, 0x0c, 0xb2, 0x3c, 0xbf, 0xa2, 0x1a, 0xd2, 0xc6, 0xd7, 0xe2, 0x4f, 0xe2,
	0x4f, 0xe3, 0xcf, 0xe2, 0xeb, 0xf1, 0x8d, 0x78, 0x26, 0xbe, 0x19, 0xdf, 0x8a, 0x3f, 0x8f, 0x49,
	0x3c, 0x1b, 0xdf, 0x8e, 0xe7, 0xe2, 0xf9, 0x78, 0x21, 0x5e, 0xfc, 0x6b, 0x46, 0xff, 0xd9, 0xf2,
	0xe2, 0x63, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0xc0, 0xc7, 0x99, 0xcf, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NoNameClient is the client API for NoName service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NoNameClient interface {
	// Armor
	GetArmorByID(ctx context.Context, in *GetArmorByIDRequest, opts ...grpc.CallOption) (*GetArmorByIDResponse, error)
	FindArmorByName(ctx context.Context, in *FindArmorByNameRequest, opts ...grpc.CallOption) (*FindArmorByNameResponse, error)
	UpdateArmor(ctx context.Context, in *UpdateArmorRequest, opts ...grpc.CallOption) (*UpdateArmorResponse, error)
	// ArmorCategory
	GetAllArmorCategory(ctx context.Context, in *GetAllArmorCategoryRequest, opts ...grpc.CallOption) (*GetAllArmorCategoryResponse, error)
	// Player
	GetPlayerByID(ctx context.Context, in *GetPlayerByIDRequest, opts ...grpc.CallOption) (*GetPlayerByIDResponse, error)
	FindPlayerByUsername(ctx context.Context, in *FindPlayerByUsernameRequest, opts ...grpc.CallOption) (*FindPlayerByUsernameResponse, error)
	GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*GetPlayerStatsResponse, error)
	GetPlayerArmors(ctx context.Context, in *GetPlayerArmorsRequest, opts ...grpc.CallOption) (*GetPlayerArmorsResponse, error)
	GetPlayerWeapons(ctx context.Context, in *GetPlayerWeaponsRequest, opts ...grpc.CallOption) (*GetPlayerWeaponsResponse, error)
	GetPlayerShips(ctx context.Context, in *GetPlayerShipsRequest, opts ...grpc.CallOption) (*GetPlayerShipsResponse, error)
	GetPlayerLastPosition(ctx context.Context, in *GetPlayerLastPositionRequest, opts ...grpc.CallOption) (*GetPlayerLastPositionResponse, error)
	SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error)
	ManagePlayerInventory(ctx context.Context, in *ManagePlayerInventoryRequest, opts ...grpc.CallOption) (*ManagePlayerInventoryResponse, error)
	GetPlayerResources(ctx context.Context, in *GetPlayerResourcesRequest, opts ...grpc.CallOption) (*GetPlayerResourcesResponse, error)
	GetPlayerItems(ctx context.Context, in *GetPlayerItemsRequest, opts ...grpc.CallOption) (*GetPlayerItemsResponse, error)
	GetPlayerEconomy(ctx context.Context, in *GetPlayerEconomyRequest, opts ...grpc.CallOption) (*GetPlayerEconomyResponse, error)
	GetRestsInfo(ctx context.Context, in *GetRestsInfoRequest, opts ...grpc.CallOption) (*GetRestsInfoResponse, error)
	EndPlayerRest(ctx context.Context, in *EndPlayerRestRequest, opts ...grpc.CallOption) (*EndPlayerRestResponse, error)
	// PlayerState
	GetPlayerStateByID(ctx context.Context, in *GetPlayerStateByIDRequest, opts ...grpc.CallOption) (*GetPlayerStateByIDResponse, error)
	GetPlayerStateToNotify(ctx context.Context, in *GetPlayerStateToNotifyRequest, opts ...grpc.CallOption) (*GetPlayerStateToNotifyResponse, error)
	CreatePlayerState(ctx context.Context, in *CreatePlayerStateRequest, opts ...grpc.CallOption) (*CreatePlayerStateResponse, error)
	UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateRequest, opts ...grpc.CallOption) (*UpdatePlayerStateResponse, error)
	DeletePlayerState(ctx context.Context, in *DeletePlayerStateRequest, opts ...grpc.CallOption) (*DeletePlayerStateResponse, error)
	// Enemy
	GetEnemyByID(ctx context.Context, in *GetEnemyByIDRequest, opts ...grpc.CallOption) (*GetEnemyByIDResponse, error)
	HitEnemy(ctx context.Context, in *HitEnemyRequest, opts ...grpc.CallOption) (*HitEnemyResponse, error)
	// Item
	GetAllItems(ctx context.Context, in *GetAllItemsRequest, opts ...grpc.CallOption) (*GetAllItemsResponse, error)
	GetItemByCategoryID(ctx context.Context, in *GetItemByCategoryIDRequest, opts ...grpc.CallOption) (*GetItemByCategoryIDResponse, error)
	UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error)
	// ItemCateogory
	GetAllItemCategories(ctx context.Context, in *GetAllItemCategoriesRequest, opts ...grpc.CallOption) (*GetAllItemCategoriesResponse, error)
	// Language
	FindLanguageBySlug(ctx context.Context, in *FindLanguageBySlugRequest, opts ...grpc.CallOption) (*FindLanguageBySlugResponse, error)
	FindLanguageBy(ctx context.Context, in *FindLanguageByRequest, opts ...grpc.CallOption) (*FindLanguageByResponse, error)
	GetLanguages(ctx context.Context, in *GetLanguagesRequest, opts ...grpc.CallOption) (*GetLanguagesResponse, error)
	// Map
	GetMapByID(ctx context.Context, in *GetMapByIDRequest, opts ...grpc.CallOption) (*GetMapByIDResponse, error)
	// NPC
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	Bank(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankResponse, error)
	Craft(ctx context.Context, in *CraftRequest, opts ...grpc.CallOption) (*CraftResponse, error)
	// Planet
	GetPlanetByCoordinate(ctx context.Context, in *GetPlanetByCoordinateRequest, opts ...grpc.CallOption) (*GetPlanetByCoordinateResponse, error)
	// Resouce
	GetResourceByID(ctx context.Context, in *GetResourceByIDRequest, opts ...grpc.CallOption) (*GetResourceByIDResponse, error)
	GetResourceByName(ctx context.Context, in *GetResourceByNameRequest, opts ...grpc.CallOption) (*GetResourceByNameResponse, error)
	DropResource(ctx context.Context, in *DropResourceRequest, opts ...grpc.CallOption) (*DropResourceResponse, error)
	// Ship
	GetShipRepairInfo(ctx context.Context, in *GetShipRepairInfoRequest, opts ...grpc.CallOption) (*GetShipRepairInfoResponse, error)
	StartShipRepair(ctx context.Context, in *StartShipRepairRequest, opts ...grpc.CallOption) (*StartShipRepairResponse, error)
	EndShipRepair(ctx context.Context, in *EndShipRepairRequest, opts ...grpc.CallOption) (*EndShipRepairResponse, error)
	GetShipExplorationInfo(ctx context.Context, in *GetShipExplorationInfoRequest, opts ...grpc.CallOption) (*GetShipExplorationInfoResponse, error)
	EndShipExploration(ctx context.Context, in *EndShipExplorationRequest, opts ...grpc.CallOption) (*EndShipExplorationResponse, error)
	// Transaction
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error)
	// Tresure
	DropTresure(ctx context.Context, in *DropTresureRequest, opts ...grpc.CallOption) (*DropTresureResponse, error)
	// Weapon
	GetWeaponByID(ctx context.Context, in *GetWeaponByIDRequest, opts ...grpc.CallOption) (*GetWeaponByIDResponse, error)
	FindWeaponByName(ctx context.Context, in *FindWeaponByNameRequest, opts ...grpc.CallOption) (*FindWeaponByNameResponse, error)
	UpdateWeapon(ctx context.Context, in *UpdateWeaponRequest, opts ...grpc.CallOption) (*UpdateWeaponResponse, error)
	// ArmorCategory
	GetAllWeaponCategory(ctx context.Context, in *GetAllWeaponCategoryRequest, opts ...grpc.CallOption) (*GetAllWeaponCategoryResponse, error)
}

type noNameClient struct {
	cc *grpc.ClientConn
}

func NewNoNameClient(cc *grpc.ClientConn) NoNameClient {
	return &noNameClient{cc}
}

func (c *noNameClient) GetArmorByID(ctx context.Context, in *GetArmorByIDRequest, opts ...grpc.CallOption) (*GetArmorByIDResponse, error) {
	out := new(GetArmorByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetArmorByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) FindArmorByName(ctx context.Context, in *FindArmorByNameRequest, opts ...grpc.CallOption) (*FindArmorByNameResponse, error) {
	out := new(FindArmorByNameResponse)
	err := c.cc.Invoke(ctx, "/NoName/FindArmorByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) UpdateArmor(ctx context.Context, in *UpdateArmorRequest, opts ...grpc.CallOption) (*UpdateArmorResponse, error) {
	out := new(UpdateArmorResponse)
	err := c.cc.Invoke(ctx, "/NoName/UpdateArmor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetAllArmorCategory(ctx context.Context, in *GetAllArmorCategoryRequest, opts ...grpc.CallOption) (*GetAllArmorCategoryResponse, error) {
	out := new(GetAllArmorCategoryResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetAllArmorCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerByID(ctx context.Context, in *GetPlayerByIDRequest, opts ...grpc.CallOption) (*GetPlayerByIDResponse, error) {
	out := new(GetPlayerByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) FindPlayerByUsername(ctx context.Context, in *FindPlayerByUsernameRequest, opts ...grpc.CallOption) (*FindPlayerByUsernameResponse, error) {
	out := new(FindPlayerByUsernameResponse)
	err := c.cc.Invoke(ctx, "/NoName/FindPlayerByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerStats(ctx context.Context, in *GetPlayerStatsRequest, opts ...grpc.CallOption) (*GetPlayerStatsResponse, error) {
	out := new(GetPlayerStatsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerArmors(ctx context.Context, in *GetPlayerArmorsRequest, opts ...grpc.CallOption) (*GetPlayerArmorsResponse, error) {
	out := new(GetPlayerArmorsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerArmors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerWeapons(ctx context.Context, in *GetPlayerWeaponsRequest, opts ...grpc.CallOption) (*GetPlayerWeaponsResponse, error) {
	out := new(GetPlayerWeaponsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerWeapons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerShips(ctx context.Context, in *GetPlayerShipsRequest, opts ...grpc.CallOption) (*GetPlayerShipsResponse, error) {
	out := new(GetPlayerShipsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerShips", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerLastPosition(ctx context.Context, in *GetPlayerLastPositionRequest, opts ...grpc.CallOption) (*GetPlayerLastPositionResponse, error) {
	out := new(GetPlayerLastPositionResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerLastPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) SignIn(ctx context.Context, in *SignInRequest, opts ...grpc.CallOption) (*SignInResponse, error) {
	out := new(SignInResponse)
	err := c.cc.Invoke(ctx, "/NoName/SignIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) ManagePlayerInventory(ctx context.Context, in *ManagePlayerInventoryRequest, opts ...grpc.CallOption) (*ManagePlayerInventoryResponse, error) {
	out := new(ManagePlayerInventoryResponse)
	err := c.cc.Invoke(ctx, "/NoName/ManagePlayerInventory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerResources(ctx context.Context, in *GetPlayerResourcesRequest, opts ...grpc.CallOption) (*GetPlayerResourcesResponse, error) {
	out := new(GetPlayerResourcesResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerResources", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerItems(ctx context.Context, in *GetPlayerItemsRequest, opts ...grpc.CallOption) (*GetPlayerItemsResponse, error) {
	out := new(GetPlayerItemsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerEconomy(ctx context.Context, in *GetPlayerEconomyRequest, opts ...grpc.CallOption) (*GetPlayerEconomyResponse, error) {
	out := new(GetPlayerEconomyResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerEconomy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetRestsInfo(ctx context.Context, in *GetRestsInfoRequest, opts ...grpc.CallOption) (*GetRestsInfoResponse, error) {
	out := new(GetRestsInfoResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetRestsInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) EndPlayerRest(ctx context.Context, in *EndPlayerRestRequest, opts ...grpc.CallOption) (*EndPlayerRestResponse, error) {
	out := new(EndPlayerRestResponse)
	err := c.cc.Invoke(ctx, "/NoName/EndPlayerRest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerStateByID(ctx context.Context, in *GetPlayerStateByIDRequest, opts ...grpc.CallOption) (*GetPlayerStateByIDResponse, error) {
	out := new(GetPlayerStateByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerStateByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlayerStateToNotify(ctx context.Context, in *GetPlayerStateToNotifyRequest, opts ...grpc.CallOption) (*GetPlayerStateToNotifyResponse, error) {
	out := new(GetPlayerStateToNotifyResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlayerStateToNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) CreatePlayerState(ctx context.Context, in *CreatePlayerStateRequest, opts ...grpc.CallOption) (*CreatePlayerStateResponse, error) {
	out := new(CreatePlayerStateResponse)
	err := c.cc.Invoke(ctx, "/NoName/CreatePlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) UpdatePlayerState(ctx context.Context, in *UpdatePlayerStateRequest, opts ...grpc.CallOption) (*UpdatePlayerStateResponse, error) {
	out := new(UpdatePlayerStateResponse)
	err := c.cc.Invoke(ctx, "/NoName/UpdatePlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) DeletePlayerState(ctx context.Context, in *DeletePlayerStateRequest, opts ...grpc.CallOption) (*DeletePlayerStateResponse, error) {
	out := new(DeletePlayerStateResponse)
	err := c.cc.Invoke(ctx, "/NoName/DeletePlayerState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetEnemyByID(ctx context.Context, in *GetEnemyByIDRequest, opts ...grpc.CallOption) (*GetEnemyByIDResponse, error) {
	out := new(GetEnemyByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetEnemyByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) HitEnemy(ctx context.Context, in *HitEnemyRequest, opts ...grpc.CallOption) (*HitEnemyResponse, error) {
	out := new(HitEnemyResponse)
	err := c.cc.Invoke(ctx, "/NoName/HitEnemy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetAllItems(ctx context.Context, in *GetAllItemsRequest, opts ...grpc.CallOption) (*GetAllItemsResponse, error) {
	out := new(GetAllItemsResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetAllItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetItemByCategoryID(ctx context.Context, in *GetItemByCategoryIDRequest, opts ...grpc.CallOption) (*GetItemByCategoryIDResponse, error) {
	out := new(GetItemByCategoryIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetItemByCategoryID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) UseItem(ctx context.Context, in *UseItemRequest, opts ...grpc.CallOption) (*UseItemResponse, error) {
	out := new(UseItemResponse)
	err := c.cc.Invoke(ctx, "/NoName/UseItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetAllItemCategories(ctx context.Context, in *GetAllItemCategoriesRequest, opts ...grpc.CallOption) (*GetAllItemCategoriesResponse, error) {
	out := new(GetAllItemCategoriesResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetAllItemCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) FindLanguageBySlug(ctx context.Context, in *FindLanguageBySlugRequest, opts ...grpc.CallOption) (*FindLanguageBySlugResponse, error) {
	out := new(FindLanguageBySlugResponse)
	err := c.cc.Invoke(ctx, "/NoName/FindLanguageBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) FindLanguageBy(ctx context.Context, in *FindLanguageByRequest, opts ...grpc.CallOption) (*FindLanguageByResponse, error) {
	out := new(FindLanguageByResponse)
	err := c.cc.Invoke(ctx, "/NoName/FindLanguageBy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetLanguages(ctx context.Context, in *GetLanguagesRequest, opts ...grpc.CallOption) (*GetLanguagesResponse, error) {
	out := new(GetLanguagesResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetLanguages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetMapByID(ctx context.Context, in *GetMapByIDRequest, opts ...grpc.CallOption) (*GetMapByIDResponse, error) {
	out := new(GetMapByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetMapByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) Bank(ctx context.Context, in *BankRequest, opts ...grpc.CallOption) (*BankResponse, error) {
	out := new(BankResponse)
	err := c.cc.Invoke(ctx, "/NoName/Bank", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) Craft(ctx context.Context, in *CraftRequest, opts ...grpc.CallOption) (*CraftResponse, error) {
	out := new(CraftResponse)
	err := c.cc.Invoke(ctx, "/NoName/Craft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetPlanetByCoordinate(ctx context.Context, in *GetPlanetByCoordinateRequest, opts ...grpc.CallOption) (*GetPlanetByCoordinateResponse, error) {
	out := new(GetPlanetByCoordinateResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetPlanetByCoordinate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetResourceByID(ctx context.Context, in *GetResourceByIDRequest, opts ...grpc.CallOption) (*GetResourceByIDResponse, error) {
	out := new(GetResourceByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetResourceByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetResourceByName(ctx context.Context, in *GetResourceByNameRequest, opts ...grpc.CallOption) (*GetResourceByNameResponse, error) {
	out := new(GetResourceByNameResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetResourceByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) DropResource(ctx context.Context, in *DropResourceRequest, opts ...grpc.CallOption) (*DropResourceResponse, error) {
	out := new(DropResourceResponse)
	err := c.cc.Invoke(ctx, "/NoName/DropResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetShipRepairInfo(ctx context.Context, in *GetShipRepairInfoRequest, opts ...grpc.CallOption) (*GetShipRepairInfoResponse, error) {
	out := new(GetShipRepairInfoResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetShipRepairInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) StartShipRepair(ctx context.Context, in *StartShipRepairRequest, opts ...grpc.CallOption) (*StartShipRepairResponse, error) {
	out := new(StartShipRepairResponse)
	err := c.cc.Invoke(ctx, "/NoName/StartShipRepair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) EndShipRepair(ctx context.Context, in *EndShipRepairRequest, opts ...grpc.CallOption) (*EndShipRepairResponse, error) {
	out := new(EndShipRepairResponse)
	err := c.cc.Invoke(ctx, "/NoName/EndShipRepair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetShipExplorationInfo(ctx context.Context, in *GetShipExplorationInfoRequest, opts ...grpc.CallOption) (*GetShipExplorationInfoResponse, error) {
	out := new(GetShipExplorationInfoResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetShipExplorationInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) EndShipExploration(ctx context.Context, in *EndShipExplorationRequest, opts ...grpc.CallOption) (*EndShipExplorationResponse, error) {
	out := new(EndShipExplorationResponse)
	err := c.cc.Invoke(ctx, "/NoName/EndShipExploration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionResponse, error) {
	out := new(CreateTransactionResponse)
	err := c.cc.Invoke(ctx, "/NoName/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) DropTresure(ctx context.Context, in *DropTresureRequest, opts ...grpc.CallOption) (*DropTresureResponse, error) {
	out := new(DropTresureResponse)
	err := c.cc.Invoke(ctx, "/NoName/DropTresure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetWeaponByID(ctx context.Context, in *GetWeaponByIDRequest, opts ...grpc.CallOption) (*GetWeaponByIDResponse, error) {
	out := new(GetWeaponByIDResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetWeaponByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) FindWeaponByName(ctx context.Context, in *FindWeaponByNameRequest, opts ...grpc.CallOption) (*FindWeaponByNameResponse, error) {
	out := new(FindWeaponByNameResponse)
	err := c.cc.Invoke(ctx, "/NoName/FindWeaponByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) UpdateWeapon(ctx context.Context, in *UpdateWeaponRequest, opts ...grpc.CallOption) (*UpdateWeaponResponse, error) {
	out := new(UpdateWeaponResponse)
	err := c.cc.Invoke(ctx, "/NoName/UpdateWeapon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noNameClient) GetAllWeaponCategory(ctx context.Context, in *GetAllWeaponCategoryRequest, opts ...grpc.CallOption) (*GetAllWeaponCategoryResponse, error) {
	out := new(GetAllWeaponCategoryResponse)
	err := c.cc.Invoke(ctx, "/NoName/GetAllWeaponCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoNameServer is the server API for NoName service.
type NoNameServer interface {
	// Armor
	GetArmorByID(context.Context, *GetArmorByIDRequest) (*GetArmorByIDResponse, error)
	FindArmorByName(context.Context, *FindArmorByNameRequest) (*FindArmorByNameResponse, error)
	UpdateArmor(context.Context, *UpdateArmorRequest) (*UpdateArmorResponse, error)
	// ArmorCategory
	GetAllArmorCategory(context.Context, *GetAllArmorCategoryRequest) (*GetAllArmorCategoryResponse, error)
	// Player
	GetPlayerByID(context.Context, *GetPlayerByIDRequest) (*GetPlayerByIDResponse, error)
	FindPlayerByUsername(context.Context, *FindPlayerByUsernameRequest) (*FindPlayerByUsernameResponse, error)
	GetPlayerStats(context.Context, *GetPlayerStatsRequest) (*GetPlayerStatsResponse, error)
	GetPlayerArmors(context.Context, *GetPlayerArmorsRequest) (*GetPlayerArmorsResponse, error)
	GetPlayerWeapons(context.Context, *GetPlayerWeaponsRequest) (*GetPlayerWeaponsResponse, error)
	GetPlayerShips(context.Context, *GetPlayerShipsRequest) (*GetPlayerShipsResponse, error)
	GetPlayerLastPosition(context.Context, *GetPlayerLastPositionRequest) (*GetPlayerLastPositionResponse, error)
	SignIn(context.Context, *SignInRequest) (*SignInResponse, error)
	ManagePlayerInventory(context.Context, *ManagePlayerInventoryRequest) (*ManagePlayerInventoryResponse, error)
	GetPlayerResources(context.Context, *GetPlayerResourcesRequest) (*GetPlayerResourcesResponse, error)
	GetPlayerItems(context.Context, *GetPlayerItemsRequest) (*GetPlayerItemsResponse, error)
	GetPlayerEconomy(context.Context, *GetPlayerEconomyRequest) (*GetPlayerEconomyResponse, error)
	GetRestsInfo(context.Context, *GetRestsInfoRequest) (*GetRestsInfoResponse, error)
	EndPlayerRest(context.Context, *EndPlayerRestRequest) (*EndPlayerRestResponse, error)
	// PlayerState
	GetPlayerStateByID(context.Context, *GetPlayerStateByIDRequest) (*GetPlayerStateByIDResponse, error)
	GetPlayerStateToNotify(context.Context, *GetPlayerStateToNotifyRequest) (*GetPlayerStateToNotifyResponse, error)
	CreatePlayerState(context.Context, *CreatePlayerStateRequest) (*CreatePlayerStateResponse, error)
	UpdatePlayerState(context.Context, *UpdatePlayerStateRequest) (*UpdatePlayerStateResponse, error)
	DeletePlayerState(context.Context, *DeletePlayerStateRequest) (*DeletePlayerStateResponse, error)
	// Enemy
	GetEnemyByID(context.Context, *GetEnemyByIDRequest) (*GetEnemyByIDResponse, error)
	HitEnemy(context.Context, *HitEnemyRequest) (*HitEnemyResponse, error)
	// Item
	GetAllItems(context.Context, *GetAllItemsRequest) (*GetAllItemsResponse, error)
	GetItemByCategoryID(context.Context, *GetItemByCategoryIDRequest) (*GetItemByCategoryIDResponse, error)
	UseItem(context.Context, *UseItemRequest) (*UseItemResponse, error)
	// ItemCateogory
	GetAllItemCategories(context.Context, *GetAllItemCategoriesRequest) (*GetAllItemCategoriesResponse, error)
	// Language
	FindLanguageBySlug(context.Context, *FindLanguageBySlugRequest) (*FindLanguageBySlugResponse, error)
	FindLanguageBy(context.Context, *FindLanguageByRequest) (*FindLanguageByResponse, error)
	GetLanguages(context.Context, *GetLanguagesRequest) (*GetLanguagesResponse, error)
	// Map
	GetMapByID(context.Context, *GetMapByIDRequest) (*GetMapByIDResponse, error)
	// NPC
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	Bank(context.Context, *BankRequest) (*BankResponse, error)
	Craft(context.Context, *CraftRequest) (*CraftResponse, error)
	// Planet
	GetPlanetByCoordinate(context.Context, *GetPlanetByCoordinateRequest) (*GetPlanetByCoordinateResponse, error)
	// Resouce
	GetResourceByID(context.Context, *GetResourceByIDRequest) (*GetResourceByIDResponse, error)
	GetResourceByName(context.Context, *GetResourceByNameRequest) (*GetResourceByNameResponse, error)
	DropResource(context.Context, *DropResourceRequest) (*DropResourceResponse, error)
	// Ship
	GetShipRepairInfo(context.Context, *GetShipRepairInfoRequest) (*GetShipRepairInfoResponse, error)
	StartShipRepair(context.Context, *StartShipRepairRequest) (*StartShipRepairResponse, error)
	EndShipRepair(context.Context, *EndShipRepairRequest) (*EndShipRepairResponse, error)
	GetShipExplorationInfo(context.Context, *GetShipExplorationInfoRequest) (*GetShipExplorationInfoResponse, error)
	EndShipExploration(context.Context, *EndShipExplorationRequest) (*EndShipExplorationResponse, error)
	// Transaction
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionResponse, error)
	// Tresure
	DropTresure(context.Context, *DropTresureRequest) (*DropTresureResponse, error)
	// Weapon
	GetWeaponByID(context.Context, *GetWeaponByIDRequest) (*GetWeaponByIDResponse, error)
	FindWeaponByName(context.Context, *FindWeaponByNameRequest) (*FindWeaponByNameResponse, error)
	UpdateWeapon(context.Context, *UpdateWeaponRequest) (*UpdateWeaponResponse, error)
	// ArmorCategory
	GetAllWeaponCategory(context.Context, *GetAllWeaponCategoryRequest) (*GetAllWeaponCategoryResponse, error)
}

// UnimplementedNoNameServer can be embedded to have forward compatible implementations.
type UnimplementedNoNameServer struct {
}

func (*UnimplementedNoNameServer) GetArmorByID(ctx context.Context, req *GetArmorByIDRequest) (*GetArmorByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArmorByID not implemented")
}
func (*UnimplementedNoNameServer) FindArmorByName(ctx context.Context, req *FindArmorByNameRequest) (*FindArmorByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindArmorByName not implemented")
}
func (*UnimplementedNoNameServer) UpdateArmor(ctx context.Context, req *UpdateArmorRequest) (*UpdateArmorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArmor not implemented")
}
func (*UnimplementedNoNameServer) GetAllArmorCategory(ctx context.Context, req *GetAllArmorCategoryRequest) (*GetAllArmorCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllArmorCategory not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerByID(ctx context.Context, req *GetPlayerByIDRequest) (*GetPlayerByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerByID not implemented")
}
func (*UnimplementedNoNameServer) FindPlayerByUsername(ctx context.Context, req *FindPlayerByUsernameRequest) (*FindPlayerByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindPlayerByUsername not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerStats(ctx context.Context, req *GetPlayerStatsRequest) (*GetPlayerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStats not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerArmors(ctx context.Context, req *GetPlayerArmorsRequest) (*GetPlayerArmorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerArmors not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerWeapons(ctx context.Context, req *GetPlayerWeaponsRequest) (*GetPlayerWeaponsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerWeapons not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerShips(ctx context.Context, req *GetPlayerShipsRequest) (*GetPlayerShipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerShips not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerLastPosition(ctx context.Context, req *GetPlayerLastPositionRequest) (*GetPlayerLastPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerLastPosition not implemented")
}
func (*UnimplementedNoNameServer) SignIn(ctx context.Context, req *SignInRequest) (*SignInResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignIn not implemented")
}
func (*UnimplementedNoNameServer) ManagePlayerInventory(ctx context.Context, req *ManagePlayerInventoryRequest) (*ManagePlayerInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManagePlayerInventory not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerResources(ctx context.Context, req *GetPlayerResourcesRequest) (*GetPlayerResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerResources not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerItems(ctx context.Context, req *GetPlayerItemsRequest) (*GetPlayerItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerItems not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerEconomy(ctx context.Context, req *GetPlayerEconomyRequest) (*GetPlayerEconomyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerEconomy not implemented")
}
func (*UnimplementedNoNameServer) GetRestsInfo(ctx context.Context, req *GetRestsInfoRequest) (*GetRestsInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestsInfo not implemented")
}
func (*UnimplementedNoNameServer) EndPlayerRest(ctx context.Context, req *EndPlayerRestRequest) (*EndPlayerRestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndPlayerRest not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerStateByID(ctx context.Context, req *GetPlayerStateByIDRequest) (*GetPlayerStateByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStateByID not implemented")
}
func (*UnimplementedNoNameServer) GetPlayerStateToNotify(ctx context.Context, req *GetPlayerStateToNotifyRequest) (*GetPlayerStateToNotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlayerStateToNotify not implemented")
}
func (*UnimplementedNoNameServer) CreatePlayerState(ctx context.Context, req *CreatePlayerStateRequest) (*CreatePlayerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlayerState not implemented")
}
func (*UnimplementedNoNameServer) UpdatePlayerState(ctx context.Context, req *UpdatePlayerStateRequest) (*UpdatePlayerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlayerState not implemented")
}
func (*UnimplementedNoNameServer) DeletePlayerState(ctx context.Context, req *DeletePlayerStateRequest) (*DeletePlayerStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlayerState not implemented")
}
func (*UnimplementedNoNameServer) GetEnemyByID(ctx context.Context, req *GetEnemyByIDRequest) (*GetEnemyByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnemyByID not implemented")
}
func (*UnimplementedNoNameServer) HitEnemy(ctx context.Context, req *HitEnemyRequest) (*HitEnemyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HitEnemy not implemented")
}
func (*UnimplementedNoNameServer) GetAllItems(ctx context.Context, req *GetAllItemsRequest) (*GetAllItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItems not implemented")
}
func (*UnimplementedNoNameServer) GetItemByCategoryID(ctx context.Context, req *GetItemByCategoryIDRequest) (*GetItemByCategoryIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemByCategoryID not implemented")
}
func (*UnimplementedNoNameServer) UseItem(ctx context.Context, req *UseItemRequest) (*UseItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseItem not implemented")
}
func (*UnimplementedNoNameServer) GetAllItemCategories(ctx context.Context, req *GetAllItemCategoriesRequest) (*GetAllItemCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllItemCategories not implemented")
}
func (*UnimplementedNoNameServer) FindLanguageBySlug(ctx context.Context, req *FindLanguageBySlugRequest) (*FindLanguageBySlugResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLanguageBySlug not implemented")
}
func (*UnimplementedNoNameServer) FindLanguageBy(ctx context.Context, req *FindLanguageByRequest) (*FindLanguageByResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLanguageBy not implemented")
}
func (*UnimplementedNoNameServer) GetLanguages(ctx context.Context, req *GetLanguagesRequest) (*GetLanguagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLanguages not implemented")
}
func (*UnimplementedNoNameServer) GetMapByID(ctx context.Context, req *GetMapByIDRequest) (*GetMapByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMapByID not implemented")
}
func (*UnimplementedNoNameServer) GetAll(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedNoNameServer) Bank(ctx context.Context, req *BankRequest) (*BankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Bank not implemented")
}
func (*UnimplementedNoNameServer) Craft(ctx context.Context, req *CraftRequest) (*CraftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Craft not implemented")
}
func (*UnimplementedNoNameServer) GetPlanetByCoordinate(ctx context.Context, req *GetPlanetByCoordinateRequest) (*GetPlanetByCoordinateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlanetByCoordinate not implemented")
}
func (*UnimplementedNoNameServer) GetResourceByID(ctx context.Context, req *GetResourceByIDRequest) (*GetResourceByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceByID not implemented")
}
func (*UnimplementedNoNameServer) GetResourceByName(ctx context.Context, req *GetResourceByNameRequest) (*GetResourceByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceByName not implemented")
}
func (*UnimplementedNoNameServer) DropResource(ctx context.Context, req *DropResourceRequest) (*DropResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropResource not implemented")
}
func (*UnimplementedNoNameServer) GetShipRepairInfo(ctx context.Context, req *GetShipRepairInfoRequest) (*GetShipRepairInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipRepairInfo not implemented")
}
func (*UnimplementedNoNameServer) StartShipRepair(ctx context.Context, req *StartShipRepairRequest) (*StartShipRepairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartShipRepair not implemented")
}
func (*UnimplementedNoNameServer) EndShipRepair(ctx context.Context, req *EndShipRepairRequest) (*EndShipRepairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndShipRepair not implemented")
}
func (*UnimplementedNoNameServer) GetShipExplorationInfo(ctx context.Context, req *GetShipExplorationInfoRequest) (*GetShipExplorationInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShipExplorationInfo not implemented")
}
func (*UnimplementedNoNameServer) EndShipExploration(ctx context.Context, req *EndShipExplorationRequest) (*EndShipExplorationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndShipExploration not implemented")
}
func (*UnimplementedNoNameServer) CreateTransaction(ctx context.Context, req *CreateTransactionRequest) (*CreateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (*UnimplementedNoNameServer) DropTresure(ctx context.Context, req *DropTresureRequest) (*DropTresureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropTresure not implemented")
}
func (*UnimplementedNoNameServer) GetWeaponByID(ctx context.Context, req *GetWeaponByIDRequest) (*GetWeaponByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeaponByID not implemented")
}
func (*UnimplementedNoNameServer) FindWeaponByName(ctx context.Context, req *FindWeaponByNameRequest) (*FindWeaponByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindWeaponByName not implemented")
}
func (*UnimplementedNoNameServer) UpdateWeapon(ctx context.Context, req *UpdateWeaponRequest) (*UpdateWeaponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWeapon not implemented")
}
func (*UnimplementedNoNameServer) GetAllWeaponCategory(ctx context.Context, req *GetAllWeaponCategoryRequest) (*GetAllWeaponCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllWeaponCategory not implemented")
}

func RegisterNoNameServer(s *grpc.Server, srv NoNameServer) {
	s.RegisterService(&_NoName_serviceDesc, srv)
}

func _NoName_GetArmorByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArmorByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetArmorByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetArmorByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetArmorByID(ctx, req.(*GetArmorByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_FindArmorByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindArmorByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).FindArmorByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/FindArmorByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).FindArmorByName(ctx, req.(*FindArmorByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_UpdateArmor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArmorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).UpdateArmor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/UpdateArmor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).UpdateArmor(ctx, req.(*UpdateArmorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetAllArmorCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllArmorCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetAllArmorCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetAllArmorCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetAllArmorCategory(ctx, req.(*GetAllArmorCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerByID(ctx, req.(*GetPlayerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_FindPlayerByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPlayerByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).FindPlayerByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/FindPlayerByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).FindPlayerByUsername(ctx, req.(*FindPlayerByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerStats(ctx, req.(*GetPlayerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerArmors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerArmorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerArmors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerArmors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerArmors(ctx, req.(*GetPlayerArmorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerWeapons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerWeaponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerWeapons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerWeapons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerWeapons(ctx, req.(*GetPlayerWeaponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerShips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerShipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerShips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerShips",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerShips(ctx, req.(*GetPlayerShipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerLastPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerLastPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerLastPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerLastPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerLastPosition(ctx, req.(*GetPlayerLastPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_SignIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).SignIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/SignIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).SignIn(ctx, req.(*SignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_ManagePlayerInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManagePlayerInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).ManagePlayerInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/ManagePlayerInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).ManagePlayerInventory(ctx, req.(*ManagePlayerInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerResources",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerResources(ctx, req.(*GetPlayerResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerItems(ctx, req.(*GetPlayerItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerEconomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerEconomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerEconomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerEconomy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerEconomy(ctx, req.(*GetPlayerEconomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetRestsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetRestsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetRestsInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetRestsInfo(ctx, req.(*GetRestsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_EndPlayerRest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndPlayerRestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).EndPlayerRest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/EndPlayerRest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).EndPlayerRest(ctx, req.(*EndPlayerRestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerStateByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStateByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerStateByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerStateByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerStateByID(ctx, req.(*GetPlayerStateByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlayerStateToNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlayerStateToNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlayerStateToNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlayerStateToNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlayerStateToNotify(ctx, req.(*GetPlayerStateToNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_CreatePlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).CreatePlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/CreatePlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).CreatePlayerState(ctx, req.(*CreatePlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_UpdatePlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).UpdatePlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/UpdatePlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).UpdatePlayerState(ctx, req.(*UpdatePlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_DeletePlayerState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePlayerStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).DeletePlayerState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/DeletePlayerState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).DeletePlayerState(ctx, req.(*DeletePlayerStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetEnemyByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnemyByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetEnemyByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetEnemyByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetEnemyByID(ctx, req.(*GetEnemyByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_HitEnemy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HitEnemyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).HitEnemy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/HitEnemy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).HitEnemy(ctx, req.(*HitEnemyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetAllItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetAllItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetAllItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetAllItems(ctx, req.(*GetAllItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetItemByCategoryID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemByCategoryIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetItemByCategoryID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetItemByCategoryID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetItemByCategoryID(ctx, req.(*GetItemByCategoryIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_UseItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).UseItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/UseItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).UseItem(ctx, req.(*UseItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetAllItemCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllItemCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetAllItemCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetAllItemCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetAllItemCategories(ctx, req.(*GetAllItemCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_FindLanguageBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLanguageBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).FindLanguageBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/FindLanguageBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).FindLanguageBySlug(ctx, req.(*FindLanguageBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_FindLanguageBy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLanguageByRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).FindLanguageBy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/FindLanguageBy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).FindLanguageBy(ctx, req.(*FindLanguageByRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetLanguages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetLanguages(ctx, req.(*GetLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetMapByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMapByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetMapByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetMapByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetMapByID(ctx, req.(*GetMapByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_Bank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).Bank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/Bank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).Bank(ctx, req.(*BankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_Craft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).Craft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/Craft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).Craft(ctx, req.(*CraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetPlanetByCoordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlanetByCoordinateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetPlanetByCoordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetPlanetByCoordinate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetPlanetByCoordinate(ctx, req.(*GetPlanetByCoordinateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetResourceByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetResourceByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetResourceByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetResourceByID(ctx, req.(*GetResourceByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetResourceByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetResourceByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetResourceByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetResourceByName(ctx, req.(*GetResourceByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_DropResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).DropResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/DropResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).DropResource(ctx, req.(*DropResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetShipRepairInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipRepairInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetShipRepairInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetShipRepairInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetShipRepairInfo(ctx, req.(*GetShipRepairInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_StartShipRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartShipRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).StartShipRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/StartShipRepair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).StartShipRepair(ctx, req.(*StartShipRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_EndShipRepair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndShipRepairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).EndShipRepair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/EndShipRepair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).EndShipRepair(ctx, req.(*EndShipRepairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetShipExplorationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShipExplorationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetShipExplorationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetShipExplorationInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetShipExplorationInfo(ctx, req.(*GetShipExplorationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_EndShipExploration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndShipExplorationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).EndShipExploration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/EndShipExploration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).EndShipExploration(ctx, req.(*EndShipExplorationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_DropTresure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTresureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).DropTresure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/DropTresure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).DropTresure(ctx, req.(*DropTresureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetWeaponByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeaponByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetWeaponByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetWeaponByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetWeaponByID(ctx, req.(*GetWeaponByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_FindWeaponByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindWeaponByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).FindWeaponByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/FindWeaponByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).FindWeaponByName(ctx, req.(*FindWeaponByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_UpdateWeapon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWeaponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).UpdateWeapon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/UpdateWeapon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).UpdateWeapon(ctx, req.(*UpdateWeaponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoName_GetAllWeaponCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllWeaponCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoNameServer).GetAllWeaponCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NoName/GetAllWeaponCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoNameServer).GetAllWeaponCategory(ctx, req.(*GetAllWeaponCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NoName_serviceDesc = grpc.ServiceDesc{
	ServiceName: "NoName",
	HandlerType: (*NoNameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArmorByID",
			Handler:    _NoName_GetArmorByID_Handler,
		},
		{
			MethodName: "FindArmorByName",
			Handler:    _NoName_FindArmorByName_Handler,
		},
		{
			MethodName: "UpdateArmor",
			Handler:    _NoName_UpdateArmor_Handler,
		},
		{
			MethodName: "GetAllArmorCategory",
			Handler:    _NoName_GetAllArmorCategory_Handler,
		},
		{
			MethodName: "GetPlayerByID",
			Handler:    _NoName_GetPlayerByID_Handler,
		},
		{
			MethodName: "FindPlayerByUsername",
			Handler:    _NoName_FindPlayerByUsername_Handler,
		},
		{
			MethodName: "GetPlayerStats",
			Handler:    _NoName_GetPlayerStats_Handler,
		},
		{
			MethodName: "GetPlayerArmors",
			Handler:    _NoName_GetPlayerArmors_Handler,
		},
		{
			MethodName: "GetPlayerWeapons",
			Handler:    _NoName_GetPlayerWeapons_Handler,
		},
		{
			MethodName: "GetPlayerShips",
			Handler:    _NoName_GetPlayerShips_Handler,
		},
		{
			MethodName: "GetPlayerLastPosition",
			Handler:    _NoName_GetPlayerLastPosition_Handler,
		},
		{
			MethodName: "SignIn",
			Handler:    _NoName_SignIn_Handler,
		},
		{
			MethodName: "ManagePlayerInventory",
			Handler:    _NoName_ManagePlayerInventory_Handler,
		},
		{
			MethodName: "GetPlayerResources",
			Handler:    _NoName_GetPlayerResources_Handler,
		},
		{
			MethodName: "GetPlayerItems",
			Handler:    _NoName_GetPlayerItems_Handler,
		},
		{
			MethodName: "GetPlayerEconomy",
			Handler:    _NoName_GetPlayerEconomy_Handler,
		},
		{
			MethodName: "GetRestsInfo",
			Handler:    _NoName_GetRestsInfo_Handler,
		},
		{
			MethodName: "EndPlayerRest",
			Handler:    _NoName_EndPlayerRest_Handler,
		},
		{
			MethodName: "GetPlayerStateByID",
			Handler:    _NoName_GetPlayerStateByID_Handler,
		},
		{
			MethodName: "GetPlayerStateToNotify",
			Handler:    _NoName_GetPlayerStateToNotify_Handler,
		},
		{
			MethodName: "CreatePlayerState",
			Handler:    _NoName_CreatePlayerState_Handler,
		},
		{
			MethodName: "UpdatePlayerState",
			Handler:    _NoName_UpdatePlayerState_Handler,
		},
		{
			MethodName: "DeletePlayerState",
			Handler:    _NoName_DeletePlayerState_Handler,
		},
		{
			MethodName: "GetEnemyByID",
			Handler:    _NoName_GetEnemyByID_Handler,
		},
		{
			MethodName: "HitEnemy",
			Handler:    _NoName_HitEnemy_Handler,
		},
		{
			MethodName: "GetAllItems",
			Handler:    _NoName_GetAllItems_Handler,
		},
		{
			MethodName: "GetItemByCategoryID",
			Handler:    _NoName_GetItemByCategoryID_Handler,
		},
		{
			MethodName: "UseItem",
			Handler:    _NoName_UseItem_Handler,
		},
		{
			MethodName: "GetAllItemCategories",
			Handler:    _NoName_GetAllItemCategories_Handler,
		},
		{
			MethodName: "FindLanguageBySlug",
			Handler:    _NoName_FindLanguageBySlug_Handler,
		},
		{
			MethodName: "FindLanguageBy",
			Handler:    _NoName_FindLanguageBy_Handler,
		},
		{
			MethodName: "GetLanguages",
			Handler:    _NoName_GetLanguages_Handler,
		},
		{
			MethodName: "GetMapByID",
			Handler:    _NoName_GetMapByID_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _NoName_GetAll_Handler,
		},
		{
			MethodName: "Bank",
			Handler:    _NoName_Bank_Handler,
		},
		{
			MethodName: "Craft",
			Handler:    _NoName_Craft_Handler,
		},
		{
			MethodName: "GetPlanetByCoordinate",
			Handler:    _NoName_GetPlanetByCoordinate_Handler,
		},
		{
			MethodName: "GetResourceByID",
			Handler:    _NoName_GetResourceByID_Handler,
		},
		{
			MethodName: "GetResourceByName",
			Handler:    _NoName_GetResourceByName_Handler,
		},
		{
			MethodName: "DropResource",
			Handler:    _NoName_DropResource_Handler,
		},
		{
			MethodName: "GetShipRepairInfo",
			Handler:    _NoName_GetShipRepairInfo_Handler,
		},
		{
			MethodName: "StartShipRepair",
			Handler:    _NoName_StartShipRepair_Handler,
		},
		{
			MethodName: "EndShipRepair",
			Handler:    _NoName_EndShipRepair_Handler,
		},
		{
			MethodName: "GetShipExplorationInfo",
			Handler:    _NoName_GetShipExplorationInfo_Handler,
		},
		{
			MethodName: "EndShipExploration",
			Handler:    _NoName_EndShipExploration_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _NoName_CreateTransaction_Handler,
		},
		{
			MethodName: "DropTresure",
			Handler:    _NoName_DropTresure_Handler,
		},
		{
			MethodName: "GetWeaponByID",
			Handler:    _NoName_GetWeaponByID_Handler,
		},
		{
			MethodName: "FindWeaponByName",
			Handler:    _NoName_FindWeaponByName_Handler,
		},
		{
			MethodName: "UpdateWeapon",
			Handler:    _NoName_UpdateWeapon_Handler,
		},
		{
			MethodName: "GetAllWeaponCategory",
			Handler:    _NoName_GetAllWeaponCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/noname.proto",
}
