// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/player_state.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamp.Timestamp

type PlayerState struct {
	ID                   uint32               `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PlayerID             uint32               `protobuf:"varint,2,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Controller           string               `protobuf:"bytes,3,opt,name=Controller,proto3" json:"Controller,omitempty"`
	Father               uint32               `protobuf:"varint,4,opt,name=Father,proto3" json:"Father,omitempty"`
	Payload              string               `protobuf:"bytes,5,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Stage                int32                `protobuf:"varint,6,opt,name=Stage,proto3" json:"Stage,omitempty"`
	ToNotify             bool                 `protobuf:"varint,7,opt,name=ToNotify,proto3" json:"ToNotify,omitempty"`
	Completed            bool                 `protobuf:"varint,8,opt,name=Completed,proto3" json:"Completed,omitempty"`
	FinishAt             *timestamp.Timestamp `protobuf:"bytes,9,opt,name=FinishAt,proto3" json:"FinishAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlayerState) Reset()         { *m = PlayerState{} }
func (m *PlayerState) String() string { return proto.CompactTextString(m) }
func (*PlayerState) ProtoMessage()    {}
func (*PlayerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{0}
}

func (m *PlayerState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerState.Unmarshal(m, b)
}
func (m *PlayerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerState.Marshal(b, m, deterministic)
}
func (m *PlayerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerState.Merge(m, src)
}
func (m *PlayerState) XXX_Size() int {
	return xxx_messageInfo_PlayerState.Size(m)
}
func (m *PlayerState) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerState.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerState proto.InternalMessageInfo

func (m *PlayerState) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PlayerState) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *PlayerState) GetController() string {
	if m != nil {
		return m.Controller
	}
	return ""
}

func (m *PlayerState) GetFather() uint32 {
	if m != nil {
		return m.Father
	}
	return 0
}

func (m *PlayerState) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *PlayerState) GetStage() int32 {
	if m != nil {
		return m.Stage
	}
	return 0
}

func (m *PlayerState) GetToNotify() bool {
	if m != nil {
		return m.ToNotify
	}
	return false
}

func (m *PlayerState) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *PlayerState) GetFinishAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishAt
	}
	return nil
}

// GetPlayerStateByID
type GetPlayerStateByIDRequest struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerStateByIDRequest) Reset()         { *m = GetPlayerStateByIDRequest{} }
func (m *GetPlayerStateByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateByIDRequest) ProtoMessage()    {}
func (*GetPlayerStateByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{1}
}

func (m *GetPlayerStateByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateByIDRequest.Unmarshal(m, b)
}
func (m *GetPlayerStateByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateByIDRequest.Merge(m, src)
}
func (m *GetPlayerStateByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateByIDRequest.Size(m)
}
func (m *GetPlayerStateByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateByIDRequest proto.InternalMessageInfo

func (m *GetPlayerStateByIDRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetPlayerStateByIDResponse struct {
	PlayerState          *PlayerState `protobuf:"bytes,1,opt,name=PlayerState,proto3" json:"PlayerState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPlayerStateByIDResponse) Reset()         { *m = GetPlayerStateByIDResponse{} }
func (m *GetPlayerStateByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateByIDResponse) ProtoMessage()    {}
func (*GetPlayerStateByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{2}
}

func (m *GetPlayerStateByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateByIDResponse.Unmarshal(m, b)
}
func (m *GetPlayerStateByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateByIDResponse.Merge(m, src)
}
func (m *GetPlayerStateByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateByIDResponse.Size(m)
}
func (m *GetPlayerStateByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateByIDResponse proto.InternalMessageInfo

func (m *GetPlayerStateByIDResponse) GetPlayerState() *PlayerState {
	if m != nil {
		return m.PlayerState
	}
	return nil
}

// GetActivePlayerStates
type GetActivePlayerStatesRequest struct {
	PlayerID             uint32   `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActivePlayerStatesRequest) Reset()         { *m = GetActivePlayerStatesRequest{} }
func (m *GetActivePlayerStatesRequest) String() string { return proto.CompactTextString(m) }
func (*GetActivePlayerStatesRequest) ProtoMessage()    {}
func (*GetActivePlayerStatesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{3}
}

func (m *GetActivePlayerStatesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivePlayerStatesRequest.Unmarshal(m, b)
}
func (m *GetActivePlayerStatesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivePlayerStatesRequest.Marshal(b, m, deterministic)
}
func (m *GetActivePlayerStatesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivePlayerStatesRequest.Merge(m, src)
}
func (m *GetActivePlayerStatesRequest) XXX_Size() int {
	return xxx_messageInfo_GetActivePlayerStatesRequest.Size(m)
}
func (m *GetActivePlayerStatesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivePlayerStatesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivePlayerStatesRequest proto.InternalMessageInfo

func (m *GetActivePlayerStatesRequest) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

type GetActivePlayerStatesResponse struct {
	States               []*PlayerState `protobuf:"bytes,1,rep,name=States,proto3" json:"States,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetActivePlayerStatesResponse) Reset()         { *m = GetActivePlayerStatesResponse{} }
func (m *GetActivePlayerStatesResponse) String() string { return proto.CompactTextString(m) }
func (*GetActivePlayerStatesResponse) ProtoMessage()    {}
func (*GetActivePlayerStatesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{4}
}

func (m *GetActivePlayerStatesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActivePlayerStatesResponse.Unmarshal(m, b)
}
func (m *GetActivePlayerStatesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActivePlayerStatesResponse.Marshal(b, m, deterministic)
}
func (m *GetActivePlayerStatesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActivePlayerStatesResponse.Merge(m, src)
}
func (m *GetActivePlayerStatesResponse) XXX_Size() int {
	return xxx_messageInfo_GetActivePlayerStatesResponse.Size(m)
}
func (m *GetActivePlayerStatesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActivePlayerStatesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActivePlayerStatesResponse proto.InternalMessageInfo

func (m *GetActivePlayerStatesResponse) GetStates() []*PlayerState {
	if m != nil {
		return m.States
	}
	return nil
}

// GetPlayerStateToNotify
type GetPlayerStateToNotifyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerStateToNotifyRequest) Reset()         { *m = GetPlayerStateToNotifyRequest{} }
func (m *GetPlayerStateToNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateToNotifyRequest) ProtoMessage()    {}
func (*GetPlayerStateToNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{5}
}

func (m *GetPlayerStateToNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateToNotifyRequest.Unmarshal(m, b)
}
func (m *GetPlayerStateToNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateToNotifyRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateToNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateToNotifyRequest.Merge(m, src)
}
func (m *GetPlayerStateToNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateToNotifyRequest.Size(m)
}
func (m *GetPlayerStateToNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateToNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateToNotifyRequest proto.InternalMessageInfo

type GetPlayerStateToNotifyResponse struct {
	PlayerStates         []*PlayerState `protobuf:"bytes,1,rep,name=PlayerStates,proto3" json:"PlayerStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetPlayerStateToNotifyResponse) Reset()         { *m = GetPlayerStateToNotifyResponse{} }
func (m *GetPlayerStateToNotifyResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayerStateToNotifyResponse) ProtoMessage()    {}
func (*GetPlayerStateToNotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{6}
}

func (m *GetPlayerStateToNotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerStateToNotifyResponse.Unmarshal(m, b)
}
func (m *GetPlayerStateToNotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerStateToNotifyResponse.Marshal(b, m, deterministic)
}
func (m *GetPlayerStateToNotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerStateToNotifyResponse.Merge(m, src)
}
func (m *GetPlayerStateToNotifyResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlayerStateToNotifyResponse.Size(m)
}
func (m *GetPlayerStateToNotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerStateToNotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerStateToNotifyResponse proto.InternalMessageInfo

func (m *GetPlayerStateToNotifyResponse) GetPlayerStates() []*PlayerState {
	if m != nil {
		return m.PlayerStates
	}
	return nil
}

// CreatePlayerState
type CreatePlayerStateRequest struct {
	PlayerState          *PlayerState `protobuf:"bytes,1,opt,name=PlayerState,proto3" json:"PlayerState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePlayerStateRequest) Reset()         { *m = CreatePlayerStateRequest{} }
func (m *CreatePlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerStateRequest) ProtoMessage()    {}
func (*CreatePlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{7}
}

func (m *CreatePlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerStateRequest.Unmarshal(m, b)
}
func (m *CreatePlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerStateRequest.Merge(m, src)
}
func (m *CreatePlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerStateRequest.Size(m)
}
func (m *CreatePlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerStateRequest proto.InternalMessageInfo

func (m *CreatePlayerStateRequest) GetPlayerState() *PlayerState {
	if m != nil {
		return m.PlayerState
	}
	return nil
}

type CreatePlayerStateResponse struct {
	PlayerState          *PlayerState `protobuf:"bytes,1,opt,name=PlayerState,proto3" json:"PlayerState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePlayerStateResponse) Reset()         { *m = CreatePlayerStateResponse{} }
func (m *CreatePlayerStateResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlayerStateResponse) ProtoMessage()    {}
func (*CreatePlayerStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{8}
}

func (m *CreatePlayerStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlayerStateResponse.Unmarshal(m, b)
}
func (m *CreatePlayerStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlayerStateResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlayerStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlayerStateResponse.Merge(m, src)
}
func (m *CreatePlayerStateResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlayerStateResponse.Size(m)
}
func (m *CreatePlayerStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlayerStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlayerStateResponse proto.InternalMessageInfo

func (m *CreatePlayerStateResponse) GetPlayerState() *PlayerState {
	if m != nil {
		return m.PlayerState
	}
	return nil
}

// UpdatePlayerState
type UpdatePlayerStateRequest struct {
	PlayerState          *PlayerState `protobuf:"bytes,1,opt,name=PlayerState,proto3" json:"PlayerState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePlayerStateRequest) Reset()         { *m = UpdatePlayerStateRequest{} }
func (m *UpdatePlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerStateRequest) ProtoMessage()    {}
func (*UpdatePlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{9}
}

func (m *UpdatePlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerStateRequest.Unmarshal(m, b)
}
func (m *UpdatePlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerStateRequest.Merge(m, src)
}
func (m *UpdatePlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerStateRequest.Size(m)
}
func (m *UpdatePlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerStateRequest proto.InternalMessageInfo

func (m *UpdatePlayerStateRequest) GetPlayerState() *PlayerState {
	if m != nil {
		return m.PlayerState
	}
	return nil
}

type UpdatePlayerStateResponse struct {
	PlayerState          *PlayerState `protobuf:"bytes,1,opt,name=PlayerState,proto3" json:"PlayerState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdatePlayerStateResponse) Reset()         { *m = UpdatePlayerStateResponse{} }
func (m *UpdatePlayerStateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayerStateResponse) ProtoMessage()    {}
func (*UpdatePlayerStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{10}
}

func (m *UpdatePlayerStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayerStateResponse.Unmarshal(m, b)
}
func (m *UpdatePlayerStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayerStateResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePlayerStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayerStateResponse.Merge(m, src)
}
func (m *UpdatePlayerStateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayerStateResponse.Size(m)
}
func (m *UpdatePlayerStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayerStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayerStateResponse proto.InternalMessageInfo

func (m *UpdatePlayerStateResponse) GetPlayerState() *PlayerState {
	if m != nil {
		return m.PlayerState
	}
	return nil
}

// DeletePlayerState
type DeletePlayerStateRequest struct {
	PlayerStateID        uint32   `protobuf:"varint,1,opt,name=PlayerStateID,proto3" json:"PlayerStateID,omitempty"`
	ForceDelete          bool     `protobuf:"varint,2,opt,name=ForceDelete,proto3" json:"ForceDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlayerStateRequest) Reset()         { *m = DeletePlayerStateRequest{} }
func (m *DeletePlayerStateRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePlayerStateRequest) ProtoMessage()    {}
func (*DeletePlayerStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{11}
}

func (m *DeletePlayerStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlayerStateRequest.Unmarshal(m, b)
}
func (m *DeletePlayerStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlayerStateRequest.Marshal(b, m, deterministic)
}
func (m *DeletePlayerStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlayerStateRequest.Merge(m, src)
}
func (m *DeletePlayerStateRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePlayerStateRequest.Size(m)
}
func (m *DeletePlayerStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlayerStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlayerStateRequest proto.InternalMessageInfo

func (m *DeletePlayerStateRequest) GetPlayerStateID() uint32 {
	if m != nil {
		return m.PlayerStateID
	}
	return 0
}

func (m *DeletePlayerStateRequest) GetForceDelete() bool {
	if m != nil {
		return m.ForceDelete
	}
	return false
}

type DeletePlayerStateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlayerStateResponse) Reset()         { *m = DeletePlayerStateResponse{} }
func (m *DeletePlayerStateResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePlayerStateResponse) ProtoMessage()    {}
func (*DeletePlayerStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c44522998cc754e, []int{12}
}

func (m *DeletePlayerStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlayerStateResponse.Unmarshal(m, b)
}
func (m *DeletePlayerStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlayerStateResponse.Marshal(b, m, deterministic)
}
func (m *DeletePlayerStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlayerStateResponse.Merge(m, src)
}
func (m *DeletePlayerStateResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePlayerStateResponse.Size(m)
}
func (m *DeletePlayerStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlayerStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlayerStateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlayerState)(nil), "player_state.PlayerState")
	proto.RegisterType((*GetPlayerStateByIDRequest)(nil), "player_state.GetPlayerStateByIDRequest")
	proto.RegisterType((*GetPlayerStateByIDResponse)(nil), "player_state.GetPlayerStateByIDResponse")
	proto.RegisterType((*GetActivePlayerStatesRequest)(nil), "player_state.GetActivePlayerStatesRequest")
	proto.RegisterType((*GetActivePlayerStatesResponse)(nil), "player_state.GetActivePlayerStatesResponse")
	proto.RegisterType((*GetPlayerStateToNotifyRequest)(nil), "player_state.GetPlayerStateToNotifyRequest")
	proto.RegisterType((*GetPlayerStateToNotifyResponse)(nil), "player_state.GetPlayerStateToNotifyResponse")
	proto.RegisterType((*CreatePlayerStateRequest)(nil), "player_state.CreatePlayerStateRequest")
	proto.RegisterType((*CreatePlayerStateResponse)(nil), "player_state.CreatePlayerStateResponse")
	proto.RegisterType((*UpdatePlayerStateRequest)(nil), "player_state.UpdatePlayerStateRequest")
	proto.RegisterType((*UpdatePlayerStateResponse)(nil), "player_state.UpdatePlayerStateResponse")
	proto.RegisterType((*DeletePlayerStateRequest)(nil), "player_state.DeletePlayerStateRequest")
	proto.RegisterType((*DeletePlayerStateResponse)(nil), "player_state.DeletePlayerStateResponse")
}

func init() { proto.RegisterFile("rpc/player_state.proto", fileDescriptor_5c44522998cc754e) }

var fileDescriptor_5c44522998cc754e = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xc5, 0x09, 0x49, 0x9d, 0x49, 0xcb, 0x61, 0x85, 0xaa, 0x4d, 0x28, 0xad, 0xb5, 0xe2, 0x60,
	0x09, 0xc9, 0x11, 0x45, 0xe2, 0x00, 0xe2, 0xd0, 0xc6, 0x4a, 0x95, 0x0b, 0x8a, 0xb6, 0x45, 0x05,
	0x2e, 0x95, 0x93, 0x4c, 0x53, 0x4b, 0x4e, 0xd6, 0xac, 0xa7, 0x48, 0xf9, 0x0e, 0x7e, 0x18, 0x65,
	0x6d, 0x87, 0x35, 0x72, 0xe1, 0x40, 0x7a, 0x9c, 0x37, 0xef, 0xcd, 0xbc, 0xbc, 0xc9, 0x1a, 0x0e,
	0x75, 0x3a, 0x1b, 0xa4, 0x49, 0xb4, 0x46, 0x7d, 0x93, 0x51, 0x44, 0x18, 0xa4, 0x5a, 0x91, 0x62,
	0xfb, 0x36, 0xd6, 0x3f, 0x59, 0x28, 0xb5, 0x48, 0x70, 0x60, 0x7a, 0xd3, 0xfb, 0xdb, 0x01, 0xc5,
	0x4b, 0xcc, 0x28, 0x5a, 0xa6, 0x39, 0x5d, 0xfc, 0x6c, 0x40, 0x77, 0x62, 0x14, 0x97, 0x1b, 0x01,
	0x7b, 0x06, 0x8d, 0x71, 0xc8, 0x1d, 0xcf, 0xf1, 0x0f, 0x64, 0x63, 0x1c, 0xb2, 0x3e, 0xb8, 0x79,
	0x7b, 0x1c, 0xf2, 0x86, 0x41, 0xb7, 0x35, 0x3b, 0x06, 0x18, 0xaa, 0x15, 0x69, 0x95, 0x24, 0xa8,
	0x79, 0xd3, 0x73, 0xfc, 0x8e, 0xb4, 0x10, 0x76, 0x08, 0xed, 0x51, 0x44, 0x77, 0xa8, 0xf9, 0x53,
	0xa3, 0x2c, 0x2a, 0xc6, 0x61, 0x6f, 0x12, 0xad, 0x13, 0x15, 0xcd, 0x79, 0xcb, 0x88, 0xca, 0x92,
	0x3d, 0x87, 0xd6, 0x25, 0x45, 0x0b, 0xe4, 0x6d, 0xcf, 0xf1, 0x5b, 0x32, 0x2f, 0x36, 0x1e, 0xae,
	0xd4, 0x27, 0x45, 0xf1, 0xed, 0x9a, 0xef, 0x79, 0x8e, 0xef, 0xca, 0x6d, 0xcd, 0x8e, 0xa0, 0x33,
	0x54, 0xcb, 0x34, 0x41, 0xc2, 0x39, 0x77, 0x4d, 0xf3, 0x37, 0xc0, 0xde, 0x81, 0x3b, 0x8a, 0x57,
	0x71, 0x76, 0x77, 0x46, 0xbc, 0xe3, 0x39, 0x7e, 0xf7, 0xb4, 0x1f, 0xe4, 0x89, 0x04, 0x65, 0x22,
	0xc1, 0x55, 0x99, 0x88, 0xdc, 0x72, 0xc5, 0x6b, 0xe8, 0x5d, 0x20, 0x59, 0xb9, 0x9c, 0xaf, 0xc7,
	0xa1, 0xc4, 0xef, 0xf7, 0x98, 0xd1, 0x9f, 0x11, 0x89, 0xaf, 0xd0, 0xaf, 0x23, 0x67, 0xa9, 0x5a,
	0x65, 0xc8, 0x3e, 0x54, 0xf2, 0x35, 0xb2, 0xee, 0x69, 0x2f, 0xa8, 0x5c, 0xce, 0x22, 0x48, 0x9b,
	0x2d, 0xde, 0xc3, 0xd1, 0x05, 0xd2, 0xd9, 0x8c, 0xe2, 0x1f, 0x68, 0xe1, 0x59, 0x69, 0xc5, 0xbe,
	0x8e, 0x53, 0xbd, 0x8e, 0x90, 0xf0, 0xf2, 0x01, 0x6d, 0xe1, 0xec, 0x0d, 0xb4, 0x73, 0x84, 0x3b,
	0x5e, 0xf3, 0xef, 0xa6, 0x0a, 0xa2, 0x38, 0x31, 0x33, 0xad, 0x4e, 0x79, 0x87, 0xc2, 0x90, 0xb8,
	0x81, 0xe3, 0x87, 0x08, 0xc5, 0xd6, 0x8f, 0xb0, 0x6f, 0xbb, 0xf9, 0xf7, 0xee, 0x0a, 0x5d, 0x5c,
	0x03, 0x1f, 0x6a, 0x8c, 0xc8, 0xfe, 0x49, 0x65, 0x1a, 0xff, 0x15, 0xf5, 0x17, 0xe8, 0xd5, 0x0c,
	0xde, 0xc5, 0x11, 0xaf, 0x81, 0x7f, 0x4e, 0xe7, 0x8f, 0x63, 0xb9, 0x66, 0xf0, 0x2e, 0x2c, 0x4f,
	0x81, 0x87, 0xb8, 0x79, 0x42, 0x35, 0x96, 0x5f, 0xc1, 0x81, 0x85, 0x6e, 0xff, 0x78, 0x55, 0x90,
	0x79, 0xd0, 0x1d, 0x29, 0x3d, 0xc3, 0x7c, 0x8c, 0xf9, 0x74, 0xb8, 0xd2, 0x86, 0xc4, 0x0b, 0xe8,
	0xd5, 0xec, 0xc8, 0xdd, 0x9f, 0xb7, 0xbe, 0x35, 0x75, 0x3a, 0x9b, 0x3c, 0x99, 0xb6, 0xcd, 0x3b,
	0x7d, 0xfb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xad, 0x6c, 0x43, 0xef, 0x04, 0x00, 0x00,
}
