// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/rarity.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Rarity struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rarity) Reset()         { *m = Rarity{} }
func (m *Rarity) String() string { return proto.CompactTextString(m) }
func (*Rarity) ProtoMessage()    {}
func (*Rarity) Descriptor() ([]byte, []int) {
	return fileDescriptor_523c65aa504136fe, []int{0}
}

func (m *Rarity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rarity.Unmarshal(m, b)
}
func (m *Rarity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rarity.Marshal(b, m, deterministic)
}
func (m *Rarity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rarity.Merge(m, src)
}
func (m *Rarity) XXX_Size() int {
	return xxx_messageInfo_Rarity.Size(m)
}
func (m *Rarity) XXX_DiscardUnknown() {
	xxx_messageInfo_Rarity.DiscardUnknown(m)
}

var xxx_messageInfo_Rarity proto.InternalMessageInfo

func (m *Rarity) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Rarity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Rarity) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func init() {
	proto.RegisterType((*Rarity)(nil), "rarity.Rarity")
}

func init() { proto.RegisterFile("rpc/rarity.proto", fileDescriptor_523c65aa504136fe) }

var fileDescriptor_523c65aa504136fe = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2a, 0x48, 0xd6,
	0x2f, 0x4a, 0x2c, 0xca, 0x2c, 0xa9, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0,
	0x94, 0x1c, 0xb8, 0xd8, 0x82, 0xc0, 0x2c, 0x21, 0x3e, 0x2e, 0x26, 0x4f, 0x17, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xde, 0x20, 0x26, 0x4f, 0x17, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54, 0x09,
	0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0x24, 0x16, 0x9c, 0x53, 0x9a, 0x2e, 0xc1, 0x0c,
	0x11, 0x03, 0xb1, 0x9d, 0x58, 0xa3, 0x98, 0x8b, 0x0a, 0x92, 0x93, 0xd8, 0xc0, 0xe6, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xa5, 0x2f, 0x8b, 0x6b, 0x00, 0x00, 0x00,
}
