// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/ship.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ship struct {
	ID                   uint32        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	PlayerID             uint32        `protobuf:"varint,3,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	RarityID             uint32        `protobuf:"varint,5,opt,name=RarityID,proto3" json:"RarityID,omitempty"`
	Rarity               *Rarity       `protobuf:"bytes,6,opt,name=Rarity,proto3" json:"Rarity,omitempty"`
	ShipCategoryID       uint32        `protobuf:"varint,7,opt,name=ShipCategoryID,proto3" json:"ShipCategoryID,omitempty"`
	ShipCategory         *ShipCategory `protobuf:"bytes,8,opt,name=ShipCategory,proto3" json:"ShipCategory,omitempty"`
	ShipStatsID          uint32        `protobuf:"varint,9,opt,name=ShipStatsID,proto3" json:"ShipStatsID,omitempty"`
	ShipStats            *ShipStats    `protobuf:"bytes,10,opt,name=ShipStats,proto3" json:"ShipStats,omitempty"`
	Equipped             bool          `protobuf:"varint,11,opt,name=Equipped,proto3" json:"Equipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Ship) Reset()         { *m = Ship{} }
func (m *Ship) String() string { return proto.CompactTextString(m) }
func (*Ship) ProtoMessage()    {}
func (*Ship) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{0}
}

func (m *Ship) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ship.Unmarshal(m, b)
}
func (m *Ship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ship.Marshal(b, m, deterministic)
}
func (m *Ship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ship.Merge(m, src)
}
func (m *Ship) XXX_Size() int {
	return xxx_messageInfo_Ship.Size(m)
}
func (m *Ship) XXX_DiscardUnknown() {
	xxx_messageInfo_Ship.DiscardUnknown(m)
}

var xxx_messageInfo_Ship proto.InternalMessageInfo

func (m *Ship) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Ship) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ship) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *Ship) GetRarityID() uint32 {
	if m != nil {
		return m.RarityID
	}
	return 0
}

func (m *Ship) GetRarity() *Rarity {
	if m != nil {
		return m.Rarity
	}
	return nil
}

func (m *Ship) GetShipCategoryID() uint32 {
	if m != nil {
		return m.ShipCategoryID
	}
	return 0
}

func (m *Ship) GetShipCategory() *ShipCategory {
	if m != nil {
		return m.ShipCategory
	}
	return nil
}

func (m *Ship) GetShipStatsID() uint32 {
	if m != nil {
		return m.ShipStatsID
	}
	return 0
}

func (m *Ship) GetShipStats() *ShipStats {
	if m != nil {
		return m.ShipStats
	}
	return nil
}

func (m *Ship) GetEquipped() bool {
	if m != nil {
		return m.Equipped
	}
	return false
}

// GetShipRepairInfo
type GetShipRepairInfoRequest struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=Ship,proto3" json:"Ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipRepairInfoRequest) Reset()         { *m = GetShipRepairInfoRequest{} }
func (m *GetShipRepairInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetShipRepairInfoRequest) ProtoMessage()    {}
func (*GetShipRepairInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{1}
}

func (m *GetShipRepairInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipRepairInfoRequest.Unmarshal(m, b)
}
func (m *GetShipRepairInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipRepairInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetShipRepairInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipRepairInfoRequest.Merge(m, src)
}
func (m *GetShipRepairInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetShipRepairInfoRequest.Size(m)
}
func (m *GetShipRepairInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipRepairInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipRepairInfoRequest proto.InternalMessageInfo

func (m *GetShipRepairInfoRequest) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

type GetShipRepairInfoResponse struct {
	NeedRepairs          bool     `protobuf:"varint,1,opt,name=NeedRepairs,proto3" json:"NeedRepairs,omitempty"`
	RepairTime           int32    `protobuf:"varint,2,opt,name=RepairTime,proto3" json:"RepairTime,omitempty"`
	QuantityResources    int32    `protobuf:"varint,3,opt,name=QuantityResources,proto3" json:"QuantityResources,omitempty"`
	TypeResources        string   `protobuf:"bytes,4,opt,name=TypeResources,proto3" json:"TypeResources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipRepairInfoResponse) Reset()         { *m = GetShipRepairInfoResponse{} }
func (m *GetShipRepairInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetShipRepairInfoResponse) ProtoMessage()    {}
func (*GetShipRepairInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{2}
}

func (m *GetShipRepairInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipRepairInfoResponse.Unmarshal(m, b)
}
func (m *GetShipRepairInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipRepairInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetShipRepairInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipRepairInfoResponse.Merge(m, src)
}
func (m *GetShipRepairInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetShipRepairInfoResponse.Size(m)
}
func (m *GetShipRepairInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipRepairInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipRepairInfoResponse proto.InternalMessageInfo

func (m *GetShipRepairInfoResponse) GetNeedRepairs() bool {
	if m != nil {
		return m.NeedRepairs
	}
	return false
}

func (m *GetShipRepairInfoResponse) GetRepairTime() int32 {
	if m != nil {
		return m.RepairTime
	}
	return 0
}

func (m *GetShipRepairInfoResponse) GetQuantityResources() int32 {
	if m != nil {
		return m.QuantityResources
	}
	return 0
}

func (m *GetShipRepairInfoResponse) GetTypeResources() string {
	if m != nil {
		return m.TypeResources
	}
	return ""
}

// StartShipRepair
type StartShipRepairRequest struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=Ship,proto3" json:"Ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartShipRepairRequest) Reset()         { *m = StartShipRepairRequest{} }
func (m *StartShipRepairRequest) String() string { return proto.CompactTextString(m) }
func (*StartShipRepairRequest) ProtoMessage()    {}
func (*StartShipRepairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{3}
}

func (m *StartShipRepairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartShipRepairRequest.Unmarshal(m, b)
}
func (m *StartShipRepairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartShipRepairRequest.Marshal(b, m, deterministic)
}
func (m *StartShipRepairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartShipRepairRequest.Merge(m, src)
}
func (m *StartShipRepairRequest) XXX_Size() int {
	return xxx_messageInfo_StartShipRepairRequest.Size(m)
}
func (m *StartShipRepairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartShipRepairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartShipRepairRequest proto.InternalMessageInfo

func (m *StartShipRepairRequest) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

type StartShipRepair struct {
	ResourceID           uint32   `protobuf:"varint,1,opt,name=ResourceID,proto3" json:"ResourceID,omitempty"`
	Quantity             int32    `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartShipRepair) Reset()         { *m = StartShipRepair{} }
func (m *StartShipRepair) String() string { return proto.CompactTextString(m) }
func (*StartShipRepair) ProtoMessage()    {}
func (*StartShipRepair) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{4}
}

func (m *StartShipRepair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartShipRepair.Unmarshal(m, b)
}
func (m *StartShipRepair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartShipRepair.Marshal(b, m, deterministic)
}
func (m *StartShipRepair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartShipRepair.Merge(m, src)
}
func (m *StartShipRepair) XXX_Size() int {
	return xxx_messageInfo_StartShipRepair.Size(m)
}
func (m *StartShipRepair) XXX_DiscardUnknown() {
	xxx_messageInfo_StartShipRepair.DiscardUnknown(m)
}

var xxx_messageInfo_StartShipRepair proto.InternalMessageInfo

func (m *StartShipRepair) GetResourceID() uint32 {
	if m != nil {
		return m.ResourceID
	}
	return 0
}

func (m *StartShipRepair) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type StartShipRepairResponse struct {
	StartShipRepair      []*StartShipRepair `protobuf:"bytes,1,rep,name=StartShipRepair,proto3" json:"StartShipRepair,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StartShipRepairResponse) Reset()         { *m = StartShipRepairResponse{} }
func (m *StartShipRepairResponse) String() string { return proto.CompactTextString(m) }
func (*StartShipRepairResponse) ProtoMessage()    {}
func (*StartShipRepairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{5}
}

func (m *StartShipRepairResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartShipRepairResponse.Unmarshal(m, b)
}
func (m *StartShipRepairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartShipRepairResponse.Marshal(b, m, deterministic)
}
func (m *StartShipRepairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartShipRepairResponse.Merge(m, src)
}
func (m *StartShipRepairResponse) XXX_Size() int {
	return xxx_messageInfo_StartShipRepairResponse.Size(m)
}
func (m *StartShipRepairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartShipRepairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartShipRepairResponse proto.InternalMessageInfo

func (m *StartShipRepairResponse) GetStartShipRepair() []*StartShipRepair {
	if m != nil {
		return m.StartShipRepair
	}
	return nil
}

// StartShipRepair
type EndShipRepairRequest struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=Ship,proto3" json:"Ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndShipRepairRequest) Reset()         { *m = EndShipRepairRequest{} }
func (m *EndShipRepairRequest) String() string { return proto.CompactTextString(m) }
func (*EndShipRepairRequest) ProtoMessage()    {}
func (*EndShipRepairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{6}
}

func (m *EndShipRepairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndShipRepairRequest.Unmarshal(m, b)
}
func (m *EndShipRepairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndShipRepairRequest.Marshal(b, m, deterministic)
}
func (m *EndShipRepairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndShipRepairRequest.Merge(m, src)
}
func (m *EndShipRepairRequest) XXX_Size() int {
	return xxx_messageInfo_EndShipRepairRequest.Size(m)
}
func (m *EndShipRepairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndShipRepairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndShipRepairRequest proto.InternalMessageInfo

func (m *EndShipRepairRequest) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

type EndShipRepairResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndShipRepairResponse) Reset()         { *m = EndShipRepairResponse{} }
func (m *EndShipRepairResponse) String() string { return proto.CompactTextString(m) }
func (*EndShipRepairResponse) ProtoMessage()    {}
func (*EndShipRepairResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{7}
}

func (m *EndShipRepairResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndShipRepairResponse.Unmarshal(m, b)
}
func (m *EndShipRepairResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndShipRepairResponse.Marshal(b, m, deterministic)
}
func (m *EndShipRepairResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndShipRepairResponse.Merge(m, src)
}
func (m *EndShipRepairResponse) XXX_Size() int {
	return xxx_messageInfo_EndShipRepairResponse.Size(m)
}
func (m *EndShipRepairResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndShipRepairResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndShipRepairResponse proto.InternalMessageInfo

// GetShipTravelInfo
type GetShipTravelInfoRequest struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=Ship,proto3" json:"Ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipTravelInfoRequest) Reset()         { *m = GetShipTravelInfoRequest{} }
func (m *GetShipTravelInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetShipTravelInfoRequest) ProtoMessage()    {}
func (*GetShipTravelInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{8}
}

func (m *GetShipTravelInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipTravelInfoRequest.Unmarshal(m, b)
}
func (m *GetShipTravelInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipTravelInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetShipTravelInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipTravelInfoRequest.Merge(m, src)
}
func (m *GetShipTravelInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetShipTravelInfoRequest.Size(m)
}
func (m *GetShipTravelInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipTravelInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipTravelInfoRequest proto.InternalMessageInfo

func (m *GetShipTravelInfoRequest) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

type GetShipTravelInfo struct {
	Planet               *Planet  `protobuf:"bytes,1,opt,name=Planet,proto3" json:"Planet,omitempty"`
	Distance             float64  `protobuf:"fixed64,2,opt,name=Distance,proto3" json:"Distance,omitempty"`
	Time                 int32    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	Fuel                 float64  `protobuf:"fixed64,4,opt,name=Fuel,proto3" json:"Fuel,omitempty"`
	Integrity            uint32   `protobuf:"varint,5,opt,name=Integrity,proto3" json:"Integrity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShipTravelInfo) Reset()         { *m = GetShipTravelInfo{} }
func (m *GetShipTravelInfo) String() string { return proto.CompactTextString(m) }
func (*GetShipTravelInfo) ProtoMessage()    {}
func (*GetShipTravelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{9}
}

func (m *GetShipTravelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipTravelInfo.Unmarshal(m, b)
}
func (m *GetShipTravelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipTravelInfo.Marshal(b, m, deterministic)
}
func (m *GetShipTravelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipTravelInfo.Merge(m, src)
}
func (m *GetShipTravelInfo) XXX_Size() int {
	return xxx_messageInfo_GetShipTravelInfo.Size(m)
}
func (m *GetShipTravelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipTravelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipTravelInfo proto.InternalMessageInfo

func (m *GetShipTravelInfo) GetPlanet() *Planet {
	if m != nil {
		return m.Planet
	}
	return nil
}

func (m *GetShipTravelInfo) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *GetShipTravelInfo) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GetShipTravelInfo) GetFuel() float64 {
	if m != nil {
		return m.Fuel
	}
	return 0
}

func (m *GetShipTravelInfo) GetIntegrity() uint32 {
	if m != nil {
		return m.Integrity
	}
	return 0
}

type GetShipTravelInfoResponse struct {
	Info                 []*GetShipTravelInfo `protobuf:"bytes,1,rep,name=Info,proto3" json:"Info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetShipTravelInfoResponse) Reset()         { *m = GetShipTravelInfoResponse{} }
func (m *GetShipTravelInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetShipTravelInfoResponse) ProtoMessage()    {}
func (*GetShipTravelInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{10}
}

func (m *GetShipTravelInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShipTravelInfoResponse.Unmarshal(m, b)
}
func (m *GetShipTravelInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShipTravelInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetShipTravelInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShipTravelInfoResponse.Merge(m, src)
}
func (m *GetShipTravelInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetShipTravelInfoResponse.Size(m)
}
func (m *GetShipTravelInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShipTravelInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShipTravelInfoResponse proto.InternalMessageInfo

func (m *GetShipTravelInfoResponse) GetInfo() []*GetShipTravelInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// EndShipTravel
type EndShipTravelRequest struct {
	Integrity            uint32   `protobuf:"varint,1,opt,name=Integrity,proto3" json:"Integrity,omitempty"`
	Tank                 float64  `protobuf:"fixed64,2,opt,name=Tank,proto3" json:"Tank,omitempty"`
	PlanetID             uint32   `protobuf:"varint,3,opt,name=PlanetID,proto3" json:"PlanetID,omitempty"`
	ShipID               uint32   `protobuf:"varint,4,opt,name=ShipID,proto3" json:"ShipID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndShipTravelRequest) Reset()         { *m = EndShipTravelRequest{} }
func (m *EndShipTravelRequest) String() string { return proto.CompactTextString(m) }
func (*EndShipTravelRequest) ProtoMessage()    {}
func (*EndShipTravelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{11}
}

func (m *EndShipTravelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndShipTravelRequest.Unmarshal(m, b)
}
func (m *EndShipTravelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndShipTravelRequest.Marshal(b, m, deterministic)
}
func (m *EndShipTravelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndShipTravelRequest.Merge(m, src)
}
func (m *EndShipTravelRequest) XXX_Size() int {
	return xxx_messageInfo_EndShipTravelRequest.Size(m)
}
func (m *EndShipTravelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EndShipTravelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EndShipTravelRequest proto.InternalMessageInfo

func (m *EndShipTravelRequest) GetIntegrity() uint32 {
	if m != nil {
		return m.Integrity
	}
	return 0
}

func (m *EndShipTravelRequest) GetTank() float64 {
	if m != nil {
		return m.Tank
	}
	return 0
}

func (m *EndShipTravelRequest) GetPlanetID() uint32 {
	if m != nil {
		return m.PlanetID
	}
	return 0
}

func (m *EndShipTravelRequest) GetShipID() uint32 {
	if m != nil {
		return m.ShipID
	}
	return 0
}

type EndShipTravelResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndShipTravelResponse) Reset()         { *m = EndShipTravelResponse{} }
func (m *EndShipTravelResponse) String() string { return proto.CompactTextString(m) }
func (*EndShipTravelResponse) ProtoMessage()    {}
func (*EndShipTravelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{12}
}

func (m *EndShipTravelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndShipTravelResponse.Unmarshal(m, b)
}
func (m *EndShipTravelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndShipTravelResponse.Marshal(b, m, deterministic)
}
func (m *EndShipTravelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndShipTravelResponse.Merge(m, src)
}
func (m *EndShipTravelResponse) XXX_Size() int {
	return xxx_messageInfo_EndShipTravelResponse.Size(m)
}
func (m *EndShipTravelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EndShipTravelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EndShipTravelResponse proto.InternalMessageInfo

// GetPlayerShips
type GetPlayerShipsRequest struct {
	PlayerID             uint32   `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerShipsRequest) Reset()         { *m = GetPlayerShipsRequest{} }
func (m *GetPlayerShipsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerShipsRequest) ProtoMessage()    {}
func (*GetPlayerShipsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{13}
}

func (m *GetPlayerShipsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerShipsRequest.Unmarshal(m, b)
}
func (m *GetPlayerShipsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerShipsRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerShipsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerShipsRequest.Merge(m, src)
}
func (m *GetPlayerShipsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerShipsRequest.Size(m)
}
func (m *GetPlayerShipsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerShipsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerShipsRequest proto.InternalMessageInfo

func (m *GetPlayerShipsRequest) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

type GetPlayerShipsResponse struct {
	Ships                []*Ship  `protobuf:"bytes,1,rep,name=Ships,proto3" json:"Ships,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerShipsResponse) Reset()         { *m = GetPlayerShipsResponse{} }
func (m *GetPlayerShipsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayerShipsResponse) ProtoMessage()    {}
func (*GetPlayerShipsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{14}
}

func (m *GetPlayerShipsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerShipsResponse.Unmarshal(m, b)
}
func (m *GetPlayerShipsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerShipsResponse.Marshal(b, m, deterministic)
}
func (m *GetPlayerShipsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerShipsResponse.Merge(m, src)
}
func (m *GetPlayerShipsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlayerShipsResponse.Size(m)
}
func (m *GetPlayerShipsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerShipsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerShipsResponse proto.InternalMessageInfo

func (m *GetPlayerShipsResponse) GetShips() []*Ship {
	if m != nil {
		return m.Ships
	}
	return nil
}

// GetPlayerShipEquipped
type GetPlayerShipEquippedRequest struct {
	PlayerID             uint32   `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerShipEquippedRequest) Reset()         { *m = GetPlayerShipEquippedRequest{} }
func (m *GetPlayerShipEquippedRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlayerShipEquippedRequest) ProtoMessage()    {}
func (*GetPlayerShipEquippedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{15}
}

func (m *GetPlayerShipEquippedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerShipEquippedRequest.Unmarshal(m, b)
}
func (m *GetPlayerShipEquippedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerShipEquippedRequest.Marshal(b, m, deterministic)
}
func (m *GetPlayerShipEquippedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerShipEquippedRequest.Merge(m, src)
}
func (m *GetPlayerShipEquippedRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlayerShipEquippedRequest.Size(m)
}
func (m *GetPlayerShipEquippedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerShipEquippedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerShipEquippedRequest proto.InternalMessageInfo

func (m *GetPlayerShipEquippedRequest) GetPlayerID() uint32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

type GetPlayerShipEquippedResponse struct {
	Ship                 *Ship    `protobuf:"bytes,1,opt,name=Ship,proto3" json:"Ship,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlayerShipEquippedResponse) Reset()         { *m = GetPlayerShipEquippedResponse{} }
func (m *GetPlayerShipEquippedResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlayerShipEquippedResponse) ProtoMessage()    {}
func (*GetPlayerShipEquippedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a527018f6722ef, []int{16}
}

func (m *GetPlayerShipEquippedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlayerShipEquippedResponse.Unmarshal(m, b)
}
func (m *GetPlayerShipEquippedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlayerShipEquippedResponse.Marshal(b, m, deterministic)
}
func (m *GetPlayerShipEquippedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlayerShipEquippedResponse.Merge(m, src)
}
func (m *GetPlayerShipEquippedResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlayerShipEquippedResponse.Size(m)
}
func (m *GetPlayerShipEquippedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlayerShipEquippedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlayerShipEquippedResponse proto.InternalMessageInfo

func (m *GetPlayerShipEquippedResponse) GetShip() *Ship {
	if m != nil {
		return m.Ship
	}
	return nil
}

func init() {
	proto.RegisterType((*Ship)(nil), "ship.Ship")
	proto.RegisterType((*GetShipRepairInfoRequest)(nil), "ship.GetShipRepairInfoRequest")
	proto.RegisterType((*GetShipRepairInfoResponse)(nil), "ship.GetShipRepairInfoResponse")
	proto.RegisterType((*StartShipRepairRequest)(nil), "ship.StartShipRepairRequest")
	proto.RegisterType((*StartShipRepair)(nil), "ship.StartShipRepair")
	proto.RegisterType((*StartShipRepairResponse)(nil), "ship.StartShipRepairResponse")
	proto.RegisterType((*EndShipRepairRequest)(nil), "ship.EndShipRepairRequest")
	proto.RegisterType((*EndShipRepairResponse)(nil), "ship.EndShipRepairResponse")
	proto.RegisterType((*GetShipTravelInfoRequest)(nil), "ship.GetShipTravelInfoRequest")
	proto.RegisterType((*GetShipTravelInfo)(nil), "ship.GetShipTravelInfo")
	proto.RegisterType((*GetShipTravelInfoResponse)(nil), "ship.GetShipTravelInfoResponse")
	proto.RegisterType((*EndShipTravelRequest)(nil), "ship.EndShipTravelRequest")
	proto.RegisterType((*EndShipTravelResponse)(nil), "ship.EndShipTravelResponse")
	proto.RegisterType((*GetPlayerShipsRequest)(nil), "ship.GetPlayerShipsRequest")
	proto.RegisterType((*GetPlayerShipsResponse)(nil), "ship.GetPlayerShipsResponse")
	proto.RegisterType((*GetPlayerShipEquippedRequest)(nil), "ship.GetPlayerShipEquippedRequest")
	proto.RegisterType((*GetPlayerShipEquippedResponse)(nil), "ship.GetPlayerShipEquippedResponse")
}

func init() { proto.RegisterFile("rpc/ship.proto", fileDescriptor_f4a527018f6722ef) }

var fileDescriptor_f4a527018f6722ef = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5f, 0x4f, 0x13, 0x41,
	0x10, 0x77, 0xfb, 0xcf, 0x76, 0x2a, 0x55, 0x36, 0x40, 0x57, 0x44, 0xd2, 0x5c, 0x0c, 0x69, 0xa2,
	0xa9, 0x09, 0x24, 0xc6, 0xf0, 0x42, 0xa2, 0x87, 0x78, 0x0f, 0x92, 0xba, 0xf0, 0xc4, 0x8b, 0x59,
	0xcb, 0x0a, 0x17, 0xeb, 0xdd, 0x71, 0xb7, 0x35, 0x21, 0xf1, 0xab, 0xf8, 0x21, 0xfc, 0x52, 0x7e,
	0x0e, 0xb3, 0xb3, 0x7b, 0xcb, 0xde, 0x55, 0x23, 0xbc, 0xcd, 0xfc, 0x66, 0x66, 0x67, 0xe6, 0x37,
	0x73, 0x73, 0x30, 0xc8, 0xb3, 0xd9, 0xcb, 0xe2, 0x32, 0xce, 0x26, 0x59, 0x9e, 0xaa, 0x94, 0xb6,
	0xb4, 0xbc, 0xf9, 0x48, 0xa3, 0xb9, 0xc8, 0x63, 0x75, 0x6d, 0xf0, 0xcd, 0x61, 0xe9, 0xf7, 0x69,
	0x26, 0x94, 0xbc, 0x48, 0xf3, 0xd2, 0xb0, 0xe6, 0x0c, 0x85, 0x12, 0xaa, 0xb0, 0x28, 0x3e, 0x90,
	0xcd, 0x45, 0x22, 0x95, 0x41, 0x82, 0xdf, 0x0d, 0x68, 0x9d, 0x5c, 0xc6, 0x19, 0x1d, 0x40, 0x23,
	0x0a, 0x19, 0x19, 0x91, 0xf1, 0x0a, 0x6f, 0x44, 0x21, 0xa5, 0xd0, 0x3a, 0x16, 0xdf, 0x24, 0x6b,
	0x8c, 0xc8, 0xb8, 0xc7, 0x51, 0xa6, 0x9b, 0xd0, 0x9d, 0xce, 0xc5, 0xb5, 0xcc, 0xa3, 0x90, 0x35,
	0xd1, 0xd3, 0xe9, 0xda, 0xc6, 0xb1, 0xb2, 0x28, 0x64, 0x6d, 0x63, 0x2b, 0x75, 0xba, 0x03, 0x1d,
	0x23, 0xb3, 0xce, 0x88, 0x8c, 0xfb, 0xbb, 0x83, 0x89, 0x6d, 0xc2, 0xa0, 0xdc, 0x5a, 0xe9, 0x0e,
	0x0c, 0x74, 0x2d, 0x6f, 0x6d, 0x2b, 0x51, 0xc8, 0xee, 0xe3, 0x4b, 0x35, 0x94, 0x1e, 0xc0, 0x03,
	0x1f, 0x61, 0x5d, 0x7c, 0xf5, 0xc9, 0xa4, 0x4a, 0x84, 0xef, 0xc2, 0x2b, 0x01, 0x74, 0x04, 0x7d,
	0xad, 0x9f, 0x68, 0x6a, 0xa2, 0x90, 0xf5, 0x30, 0x8b, 0x0f, 0xd1, 0x3d, 0xe8, 0x39, 0x95, 0x01,
	0xbe, 0xbf, 0x3e, 0xf1, 0xf8, 0x74, 0x46, 0x7e, 0xe3, 0xa7, 0x39, 0x38, 0xbc, 0x5a, 0xc4, 0x59,
	0x26, 0xcf, 0x59, 0x7f, 0x44, 0xc6, 0x5d, 0xee, 0xf4, 0x60, 0x1f, 0xd8, 0x91, 0x54, 0xda, 0x97,
	0xcb, 0x4c, 0xc4, 0x79, 0x94, 0x7c, 0x49, 0xb9, 0xbc, 0x5a, 0xc8, 0x42, 0xd1, 0x6d, 0x33, 0x03,
	0x64, 0xbf, 0xbf, 0x0b, 0x98, 0x07, 0x33, 0x70, 0xc4, 0x83, 0x5f, 0x04, 0x1e, 0xff, 0x25, 0xb8,
	0xc8, 0xd2, 0xa4, 0x90, 0xba, 0x99, 0x63, 0x29, 0xcf, 0x8d, 0xa5, 0xc0, 0x47, 0xba, 0xdc, 0x87,
	0xe8, 0x36, 0x80, 0x11, 0x4f, 0x63, 0x3b, 0xd1, 0x36, 0xf7, 0x10, 0xfa, 0x02, 0x56, 0x3f, 0x2e,
	0x44, 0xa2, 0xf4, 0x2c, 0x64, 0x91, 0x2e, 0xf2, 0x99, 0x2c, 0x70, 0xc0, 0x6d, 0xbe, 0x6c, 0xa0,
	0xcf, 0x60, 0xe5, 0xf4, 0x3a, 0x93, 0x37, 0x9e, 0x2d, 0x5c, 0x91, 0x2a, 0x18, 0xbc, 0x86, 0x8d,
	0x13, 0x25, 0x72, 0xaf, 0xe8, 0xdb, 0x76, 0xfb, 0x01, 0x1e, 0xd6, 0x22, 0x4d, 0x03, 0xe6, 0x65,
	0xb7, 0xa4, 0x1e, 0xa2, 0x89, 0x2f, 0xeb, 0xb4, 0xed, 0x39, 0x3d, 0x38, 0x83, 0xe1, 0x52, 0x21,
	0x96, 0xb9, 0x83, 0xa5, 0x4c, 0x8c, 0x8c, 0x9a, 0x6e, 0xd4, 0x93, 0x7a, 0x5c, 0xdd, 0x3b, 0x78,
	0x05, 0x6b, 0x87, 0xc9, 0xf9, 0xdd, 0x5b, 0x1c, 0xc2, 0x7a, 0x2d, 0xce, 0x54, 0xe4, 0x6d, 0xc9,
	0x69, 0x2e, 0xbe, 0xcb, 0xf9, 0x5d, 0xb6, 0xe4, 0x27, 0x81, 0xd5, 0xa5, 0x60, 0xfd, 0xed, 0x4d,
	0xf1, 0x83, 0xb7, 0x71, 0x83, 0x89, 0xfd, 0xfe, 0x0d, 0xca, 0xad, 0x55, 0x53, 0x18, 0xc6, 0x85,
	0x12, 0xc9, 0xcc, 0x6c, 0x08, 0xe1, 0x4e, 0xd7, 0xb7, 0x00, 0x37, 0xc7, 0xac, 0x04, 0xca, 0x1a,
	0x7b, 0xb7, 0x90, 0x73, 0x1c, 0x3e, 0xe1, 0x28, 0xd3, 0x2d, 0xe8, 0x45, 0x89, 0x92, 0x17, 0xf8,
	0xa9, 0x9b, 0x23, 0x70, 0x03, 0x04, 0xef, 0xdd, 0x12, 0xfb, 0xbd, 0xd9, 0x51, 0x3c, 0x87, 0x96,
	0xd6, 0x2d, 0xff, 0x43, 0xd3, 0xdc, 0xb2, 0x3b, 0x3a, 0x05, 0x3f, 0x1c, 0xed, 0xc6, 0x54, 0x32,
	0x54, 0xc9, 0x4f, 0x6a, 0xf9, 0xb1, 0x0b, 0x91, 0x7c, 0xb5, 0xdd, 0xa1, 0x6c, 0x2f, 0x5a, 0x22,
	0x55, 0xe5, 0xa2, 0xa1, 0x4e, 0x37, 0xa0, 0xa3, 0x53, 0x44, 0x21, 0xf6, 0xb8, 0xc2, 0xad, 0xe6,
	0x0d, 0xaf, 0xcc, 0x6e, 0x87, 0xb7, 0x07, 0xeb, 0x47, 0x52, 0x99, 0x8b, 0xa8, 0xcd, 0x45, 0x59,
	0x97, 0x7f, 0x37, 0x49, 0xf5, 0x6e, 0x06, 0xfb, 0xb0, 0x51, 0x0f, 0x72, 0xdf, 0x75, 0x1b, 0x01,
	0xcb, 0x89, 0x3f, 0x70, 0x63, 0x08, 0xf6, 0x61, 0xab, 0x12, 0x5b, 0x1e, 0x9b, 0xdb, 0xe4, 0x3d,
	0x80, 0xa7, 0xff, 0x88, 0xb5, 0xe9, 0xff, 0xb3, 0x6e, 0x6f, 0xda, 0x67, 0xcd, 0x3c, 0x9b, 0x4d,
	0xef, 0x4d, 0xc9, 0xb4, 0x31, 0x6d, 0x7e, 0xee, 0xe0, 0xff, 0x64, 0xef, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x72, 0x84, 0x57, 0xdd, 0xba, 0x06, 0x00, 0x00,
}
