// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/ship_category.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShipCategory struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=Slug,proto3" json:"Slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipCategory) Reset()         { *m = ShipCategory{} }
func (m *ShipCategory) String() string { return proto.CompactTextString(m) }
func (*ShipCategory) ProtoMessage()    {}
func (*ShipCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_51b568ac7e5fde54, []int{0}
}

func (m *ShipCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipCategory.Unmarshal(m, b)
}
func (m *ShipCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipCategory.Marshal(b, m, deterministic)
}
func (m *ShipCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipCategory.Merge(m, src)
}
func (m *ShipCategory) XXX_Size() int {
	return xxx_messageInfo_ShipCategory.Size(m)
}
func (m *ShipCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipCategory.DiscardUnknown(m)
}

var xxx_messageInfo_ShipCategory proto.InternalMessageInfo

func (m *ShipCategory) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ShipCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipCategory) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func init() {
	proto.RegisterType((*ShipCategory)(nil), "ship_category.ShipCategory")
}

func init() { proto.RegisterFile("rpc/ship_category.proto", fileDescriptor_51b568ac7e5fde54) }

var fileDescriptor_51b568ac7e5fde54 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x2a, 0x48, 0xd6,
	0x2f, 0xce, 0xc8, 0x2c, 0x88, 0x4f, 0x4e, 0x2c, 0x49, 0x4d, 0xcf, 0x2f, 0xaa, 0xd4, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x45, 0x11, 0x54, 0x72, 0xe3, 0xe2, 0x09, 0xce, 0xc8, 0x2c, 0x70,
	0x86, 0xf2, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x98,
	0x3c, 0x5d, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x90, 0x58, 0x70, 0x4e, 0x69, 0xba, 0x04, 0x33, 0x44, 0x0c, 0xc4, 0x76, 0x62,
	0x8d, 0x62, 0x2e, 0x2a, 0x48, 0x4e, 0x62, 0x03, 0x5b, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xa5, 0xfc, 0x12, 0x9a, 0x7f, 0x00, 0x00, 0x00,
}
